### ISSUE TITLE
existingThoughtMove: Pending merged thoughts deleted

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1026]
## Steps to Reproduce

``` 
- a
  - b
    - c
- d
  - b
    - e
``` 

1. Paste the above thoughts
2. Set the cursor to null
3. Refresh the page
4. Set the cursor on `a` to expand it
5. Move `a/b` into `d`

## Current Behavior

- a
- d
  - b
    - c

## Expected Behavior

- a
- d
  - b
    - e
    - c

## Notes

[flushMoves](https://github.com/cybersemics/em/blob/b2bfc9e110185c4a823ff81e716a64cf25b19169/src/redux-middleware/pushQueue.ts#L110) in the `pushQueue` only uses `pathOld`, but should also flush `pathNew`.

Analyze what occurs in between the first 'existingThoughtMove` (in-memory thoughts) and the second (pending thoughts) to confirm the existing approach will still work if merging pending.

**Comment by raineorshine** [comment]
You've probably already realized this, but the solution can't go in `flushMoves` like we imagined. As you know, `pendingMoves` only contains paths from the source of the move. If all source paths are loaded already, then `pendingMoves` will be empty, but the destination may still have pending moves. In the case that we were analyzing, it only worked because `a/b/c/d` was pending, but that is not a given.

It feels like `flushMoves` is the right place to do the `pull`, but it needs to be called earlier than pending thoughts. My suggestion is for `existingThoughtMoves` to populate `pendingMoves` with the first conflict it encounters and short circuit additional recursive moves. They will be moved when `flushMoves` calls `existingThoughtMoves` the second time around. Let me know if you have any questions about this approach and curious to hear your thoughts.

**Comment by anmolarora1** [comment]
@raineorshine While the [addition of pendingPulls](https://github.com/cybersemics/em/pull/1050/commits/639c7b28e0e0e337094ada5a8770e5ad840d4135) (the proposed solution) handles the fetching and merging of thoughts correctly, it results in duplication of ranks, which is unintended. We discussed a solution for this in our last call that involves updating the ranks in [Pushqueue](https://github.com/cybersemics/em/blob/639c7b28e0e0e337094ada5a8770e5ad840d4135/src/redux-middleware/pushQueue.ts#L143) middleware based on the status of `PendingPulls` field (if there are any pending pulls, update the ranks of the `newPath`). However, that doesn't work for the nested thoughts because our existing implementation of `existingThoughtMove` computes and triggers thought updates ([based on the source context's information](https://github.com/cybersemics/em/blob/639c7b28e0e0e337094ada5a8770e5ad840d4135/src/reducers/existingThoughtMove.ts#L139)) before pushQueue gets triggered. So there's no way to stop that unless we choose to span the recursion logic between `existingThoughtMove` and `pushQueue`(which is ugly).

That said, I could think of two options for making it work that doesn't require a massive refactor (or making `existingThoughtMove` even more convoluted) - 
1. We introduce a new middleware that identifies any `existingThoughtMove` action and loads all the pending thoughts belonging to source and destination contexts, ensuring that they're available in state before the `existingThoughtMove` reducer gets fired. Or, we can use the existing `pullQueue` middleware to handle that.
2. We fetch the thoughts within the `existingThoughtMove` reducer (doesn't seem ideal)

**Comment by raineorshine** [comment]
> 1. We introduce a new middleware that identifies any `existingThoughtMove` action and loads all the pending thoughts belonging to source and destination contexts, ensuring that they're available in state before the `existingThoughtMove` reducer gets fired. Or, we can use the existing `pullQueue` middleware to handle that.

That might as well go in the `pullQueue`, since it is responsible for pulling in pending thoughts.

> 2\. We fetch the thoughts within the `existingThoughtMove` reducer (doesn't seem ideal)

Agreed, let's avoid spoiling our reducers with side effects.

---

Here's an idea. The rank duplication can only happen on pending thoughts (or perhaps their children), i.e. at the "boundary" between loaded and unloaded. If the thoughts are loaded into memory, then the initial `existingThoughtMove` will calculate the correct ranks. If the thoughts are not in memory at all, then no duplicates can occur, since they don't exist locally yet. So that leads me to the conclusion stated above, that rank duplication can only happen "on" pending thoughts (or their children, depending on how we look at it). Is that true?

If so, what about just stopping the first `existingThoughtMove` "short", i.e. one level up from where the ranks would conflict. Then there will be no duplicate ranks on the first move, and the second `existingThoughtMove` will have all the data loaded into memory. We can keep the current architecture, just adjust where the cutoff is on the first "existingThoughtMove` to avoid the rank conflicts. Thoughts?

Another option is to simply "cancel" the first `existingThoughtMove`, pull all descendants, then do a full `existingThoughtMove`. This has the advantage of being more atomic, but the disadvantage of no visible change on the client until the thoughts are fully loaded (The existing approach is mostly hidden to the user since the second call is happening on pending thoughts that are likely invisible).

**Comment by raineorshine** [comment]
> If so, what about just stopping the first `existingThoughtMove` "short", i.e. one level up from where the ranks would conflict. Then there will be no duplicate ranks on the first move, and the second `existingThoughtMove` will have all the data loaded into memory. We can keep the current architecture, just adjust where the cutoff is on the first "existingThoughtMove` to avoid the rank conflicts. Thoughts?

We may have discussed this in one of our calls, but could you remind me of our conclusion about this suggestion?

> Another option is to simply "cancel" the first `existingThoughtMove`, pull all descendants, then do a full `existingThoughtMove`. This has the advantage of being more atomic, but the disadvantage of no visible change on the client until the thoughts are fully loaded (The existing approach is mostly hidden to the user since the second call is happening on pending thoughts that are likely invisible).

I take responsibility for suggesting this as a valid option. If I had thought through it I would have known that it would result in an unacceptable user experience. It would have saved you some time. My apologies!

**Comment by anmolarora1** [comment]
> > If so, what about just stopping the first `existingThoughtMove` "short", i.e. one level up from where the ranks would conflict. Then there will be no duplicate ranks on the first move, and the second `existingThoughtMove` will have all the data loaded into memory. We can keep the current architecture, just adjust where the cutoff is on the first "existingThoughtMove` to avoid the rank conflicts. Thoughts?
> 
> We may have discussed this in one of our calls, but could you remind me of our conclusion about this suggestion?

Yes, we did discuss that and the reason for not taking that approach was to avoid any additional complexities in the `existingThoughtMove` reducer which is convoluted already. 
Another reason -
The new ranks are always computed for the source thoughts. In a scenario where the source is loaded but the destination context is pending, the ranks would be computer before even the destination context gets loaded because it can only be done in the middleware (in order to keep reducers free from side-effects), just like we're doing for [the source context](https://github.com/cybersemics/em/blob/58383aa7477305bd1866072c39cffe8e7ce7c26f/src/redux-middleware/pushQueue.ts#L123).
Consider this example -
```
- a
  - b
    - c
    - o
- d
  - b
    - e (pending)
    - o (pending)
```
Going with the suggested approach, we can short circuit the existingThoughtMove(ETM) after moving [a, b] to [d, b], load the pending thoughts through the middleware, and call ETM again. However, this call gets initiated from the pushQueue and in order to call it with the correct params (from where we left/child updates), we'd need to calculate the children in the middleware (which isn't what we want). 
If we simply short-circuit it before making any moves, it becomes similar to the [approach that we tried](https://github.com/cybersemics/em/pull/1065).



> > Another option is to simply "cancel" the first `existingThoughtMove`, pull all descendants, then do a full `existingThoughtMove`. This has the advantage of being more atomic, but the disadvantage of no visible change on the client until the thoughts are fully loaded (The existing approach is mostly hidden to the user since the second call is happening on pending thoughts that are likely invisible).
> 
> I take responsibility for suggesting this as a valid option. If I had thought through it I would have known that it would result in an unacceptable user experience. It would have saved you some time. My apologies!

**Comment by raineorshine** [comment]
> Yes, we did discuss that and the reason for not taking that approach was to avoid any additional complexities in the `existingThoughtMove` reducer which is convoluted already.

Okay, thanks. I agree, it's not pretty, and it would be nice if we could avoid that.

> we'd need to calculate the children in the middleware (which isn't what we want).

I'm not clear which children you're referring to, but it might not matter because I like your proposed solution! I'm with you in that the second ETM initiated by the `pushQueue` would need to provide the correct rank to resume moves after the short circuit.

> The solution that I'd propose is to let the ETM move all the visible thoughts, load the pending descendants (through middleware), and call ETM with the descendants loaded as done in[ this PR ](https://github.com/cybersemics/em/pull/1050) To solve the rank issue, we'd recompute the ranks of the source's children in the [second pass of ETM](https://github.com/cybersemics/em/blob/639c7b28e0e0e337094ada5a8770e5ad840d4135/src/redux-middleware/pushQueue.ts#L144) because the rank calculation cannot go wrong with all the thoughts (from both source and descendant) present in the state.
> That seems like a good way to solve the problem with minimal disruptions. What do you think?

I like the idea. It has the benefit of making the first move atomic and deferring the merging logic until after the pending thoughts are loaded.

A couple questions:

1. If all of the source thoughts are moved in the first pass, then what exactly is getting moved in the second pass? Is ETM just used to fix the broken ranks?
2. Could you explain a bit more how it would handle conflicting ranks at multiple levels?

e.g. Something like this (although some levels below may need more children to create actual ordering issues):

```
- a
  - b
    - c
      - o
        - p
- d
  - b
    - c (pending)
      - o (pending)
        - q (pending)
```

FYI We should still avoid an infinite `pull` on the destination. If the source has maxDepth 10 then we should pull with maxDepth 10 since we know there can be no conflicts beyond that.

**Comment by anmolarora1** [comment]
> > Yes, we did discuss that and the reason for not taking that approach was to avoid any additional complexities in the `existingThoughtMove` reducer which is convoluted already.
> 
> Okay, thanks. I agree, it's not pretty, and it would be nice if we could avoid that.
> 
> > we'd need to calculate the children in the middleware (which isn't what we want).
> 
> I'm not clear which children you're referring to, but it might not matter because I like your proposed solution! I'm with you in that the second ETM initiated by the `pushQueue` would need to provide the correct rank to resume moves after the short circuit.
> 
> > The solution that I'd propose is to let the ETM move all the visible thoughts, load the pending descendants (through middleware), and call ETM with the descendants loaded as done in[ this PR ](https://github.com/cybersemics/em/pull/1050) To solve the rank issue, we'd recompute the ranks of the source's children in the [second pass of ETM](https://github.com/cybersemics/em/blob/639c7b28e0e0e337094ada5a8770e5ad840d4135/src/redux-middleware/pushQueue.ts#L144) because the rank calculation cannot go wrong with all the thoughts (from both source and descendant) present in the state.
> > That seems like a good way to solve the problem with minimal disruptions. What do you think?
> 
> I like the idea. It has the benefit of making the first move atomic and deferring the merging logic until after the pending thoughts are loaded.
> 
> A couple questions:
> 
> 1. If all of the source thoughts are moved in the first pass, then what exactly is getting moved in the second pass? Is ETM just used to fix the broken ranks?

We can only move the first level of source thoughts in the first pass, because if we update thoughts for any level beyond that, they can get overridden when the destination's thoughts.
for instance
`
- a
  - b
    - c
      - o
        - p
      - 2
    - t
- d
  - b
    - c (pending)
      - o
        - q
      - 1
    - x (pending)
`

If we update `[a, b]` -> `[d, b]`, `[a, b, c]` -> `[d, b, c]` and so on, we can't [retrieve the children](https://github.com/cybersemics/em/blob/58383aa7477305bd1866072c39cffe8e7ce7c26f/src/reducers/existingThoughtMove.ts#L143) of context [a, b] in the second pass because the context's been overritten in the first pass. But we need those children. But we need them in order to update the ranks.
So, we only move the path that's visible and non-conflicting (among the source and descendant) - `[a, b]` -> `[d, b]` in this case.

  


> 2. Could you explain a bit more how it would handle conflicting ranks at multiple levels?
> 
> e.g. Something like this (although some levels below may need more children to create actual ordering issues):
> 
> ```
> - a
>   - b
>     - c
>       - o
>         - p
> - d
>   - b
>     - c (pending)
>       - o (pending)
>         - q (pending)
> ```
> 

Let's consider the same example which can produce rank conflicts at multiple levels.
`
- a
  - b
    - c
      - o
        - p (pending)
      - 2
    - t
- d
  - b
    - c (pending)
      - o (pending)
        - q (pending)
      - 1 (pending)
    - x (pending)
`

Assuming we pull with maxDepth 2

First pass moves - `[a, b]` -> `[d, b]`
Note - Context `a` gets overwritten but we don't need that for the next pass
Load the desecdants (next 2 levels)

Second pass moves - 
`[a, b, c]` -> `[d, b, c]`
`[a, b, t]` -> `[d, b, t]`
`[a, b, c, o]` -> `[d, b, c, o]`
`[a, b, c, 1]` -> `[d, b, c, 1]`
Note - Contexts `[a,b]`, `[a, b, c]` and `[a, b, t]` get overwritten but we don't need them for the next pass
Load the desecdants (next 2 levels)

Third pass moves - 
`[a, b, c, o, p]` -> `[d, b, c, o, p]`
No more loading needed because neither source nor descendants are pending


> FYI We should still avoid an infinite `pull` on the destination. If the source has maxDepth 10 then we should pull with maxDepth 10 since we know there can be no conflicts beyond that.

As explained above, we don't need to do an `Infinite pull`. However, I'm not sure how can we determine the max depth of source, or if we really need to do that? FYI, the source can be pending as well (as per the example that I've shared).

**Comment by raineorshine** [comment]
> We can only move the first level of source thoughts in the first pass, because if we update thoughts for any level beyond that, they can get overridden when the destination's thoughts.

I think we can move up to, but not including, the first pending thought. The number of levels depend partly on the `BUFFER_DEPTH` (which is currently 2) and partly on the user's activity (they may have navigated a few levels into the destination earlier and so there could be, say, 4 levels in state before a pending thought is hit.

> If we update `[a, b]` -> `[d, b]`, `[a, b, c]` -> `[d, b, c]` and so on, we can't [retrieve the children](https://github.com/cybersemics/em/blob/58383aa7477305bd1866072c39cffe8e7ce7c26f/src/reducers/existingThoughtMove.ts#L143) of context [a, b] in the second pass because the context's been overritten in the first pass. But we need those children. But we need them in order to update the ranks.
> So, we only move the path that's visible and non-conflicting (among the source and descendant) - `[a, b]` -> `[d, b]` in this case.

That makes sense

> Third pass moves

I thought there were only 2 passes: the first pass when the user executes the move, and the second pass after the correct thoughts in the source and destination are pulled in to complete the move. What is a third pass?

> As explained above, we don't need to do an `Infinite pull`. However, I'm not sure how can we determine the max depth of source, or if we really need to do that? FYI, the source can be pending as well (as per the example that I've shared).

We would have to traverse the source after all pending source thoughts are loaded. We could set a limit on this, but in the most common cases it will be small.

**Comment by anmolarora1** [comment]
> Thanks for the thorough description!
> 
> > We can only move the first level of source thoughts in the first pass, because if we update thoughts for any level beyond that, they can get overridden when the destination's thoughts.
> 
> I think we can move up to, but not including, the first pending thought. In the example case, it is just the first level, but it could be more. The number of levels depend partly on the `BUFFER_DEPTH` (which is currently 2 and will be increased as performance improved) and partly on the user's activity (they may have navigated a few levels into the destination earlier and so there could be, say, 4 levels in state before a pending thought is hit.
> 
That's correct, and that precisely matches the plan. Sorry for the incomplete description but it was primarily based on the example.


> > If we update `[a, b]` -> `[d, b]`, `[a, b, c]` -> `[d, b, c]` and so on, we can't [retrieve the children](https://github.com/cybersemics/em/blob/58383aa7477305bd1866072c39cffe8e7ce7c26f/src/reducers/existingThoughtMove.ts#L143) of context [a, b] in the second pass because the context's been overritten in the first pass. But we need those children. But we need them in order to update the ranks.
> > So, we only move the path that's visible and non-conflicting (among the source and descendant) - `[a, b]` -> `[d, b]` in this case.
> 
> That makes sense
> 
> > Third pass moves
> 
> I thought there were only 2 passes: the first pass when the user executes the move, and the second pass after the correct thoughts in the source and destination are pulled in to complete the move. What is a third pass?
> 

The number of passes would depend on 2 things - 
1) The depth of the source/destination contexts 
2) How many levels of thoughts do we pull after each pass

For example, the destination depth is 15 and the source depth is 4, we'd need `Math.ceil(15/4)` (4) passes to load the destination completely unless we pull all destination thoughts at once `maxDepth: Infinite` approach.


> If you are suggesting a recursive algorithm, why not pull the necessary destination thoughts all at once, like the `pendingMoves` source pull logic? It seems like O(depth) passes with all the throttling would be pretty slow.
> 
Agreed. We need to decide one of the 2 approaches - 
1) pull all descendants at once 
2) pull with `maxDepth = source depth` and recurse (as described above)



> > As explained above, we don't need to do an `Infinite pull`. However, I'm not sure how can we determine the max depth of source, or if we really need to do that? FYI, the source can be pending as well (as per the example that I've shared).
> 
> We would have to traverse the source after all pending source thoughts are loaded. We could set a limit on this, but in the most common cases it will be small.


The source and destination thoughts are loaded in the same place ([pushQueue middleware](https://github.com/cybersemics/em/blob/639c7b28e0e0e337094ada5a8770e5ad840d4135/src/redux-middleware/pushQueue.ts#L119-L141)). So we can only traverse the source thoughts that are loaded. We also need to specify a limit for the source thoughts, which is [currently set to infinity](https://github.com/cybersemics/em/blob/5f0a1aacb117a30752fa51d5576766b0d414ba1c/src/redux-middleware/pushQueue.ts#L123). I'd love to hear your thoughts, but based on my understanding so far, I think it'd be good to use either a fixed number or keep it infinite for now.

**Comment by raineorshine** [comment]
> That's correct, and that precisely matches the plan. Sorry for the incomplete description but it was primarily based on the example.

Great!

> pull with maxDepth = source depth and recurse (as described above)

I’d like to double check that we’re talking about the same thing. When you say recurse, do you mean the number of async pulls or do you mean a synchronous traversal to fix the ranks? Same question for what you mean by “passes”. Thanks!

> The source and destination thoughts are loaded in the same place (pushQueue middleware). So we can only traverse the source thoughts that are loaded.

We can calculate the source depth after pulling the source, and do a separate pull for the destination. It’s only O(n + 2c) instead of O(n + c), where c is the overhead from separate pull invocations. 

> We also need to specify a limit for the source thoughts, which is currently set to infinity. I'd love to hear your thoughts, but based on my understanding so far, I think it'd be good to use either a fixed number or keep it infinite for now.

Due to the current architectural, we have to modify all descendants when a thought is modified. So unfortunately we have to pull all the source. At least the running time is intuitive  to the user: the bigger the the thought, the longer it takes to move.

**Comment by anmolarora1** [comment]
> > That's correct, and that precisely matches the plan. Sorry for the incomplete description but it was primarily based on the example.
> 
> Great!
> 
> > pull with maxDepth = source depth and recurse (as described above)
> 
> I’d like to double check that we’re talking about the same thing. When you say recurse, do you mean the number of async pulls or do you mean a synchronous traversal to fix the ranks? Same question for what you mean by “passes”. Thanks!

A `pass` here refers to each `existingThoughtMove` operation (`sync`) that would move all the visible, non-conflicting source thoughts to the destination. 
Each pass is followed by a `flushMoves` operation (`async`) where we load the pending source/descendant thoughts (if any) and run the pass again (if any new thoughts were loaded in the flushMoves, they get moved. Otherwise, the ranks of the previously moved thoughts are fixed).
I hope that explains.

> 
> > The source and destination thoughts are loaded in the same place (pushQueue middleware). So we can only traverse the source thoughts that are loaded.
> 
> We can calculate the source depth after pulling the source, and do a separate pull for the destination. It’s only O(n + 2c) instead of O(n + c), where c is the overhead from separate pull invocations.

Yes, we can calculate the source depth after pulling the source 
But there might be cases when we don't need to pull the source context at all (if it's already loaded). So we'd have to introduce another value in the [PushBatch](https://github.com/cybersemics/em/blob/354c6f32b2ea0ad02c480b36a881c88a5436f2b2/src/util/initialState.ts#L25) to allow passing the `depth` of the source from `ETM` to `flushMoves`, which'd be used at the time of [loading destination thoughts](https://github.com/cybersemics/em/blob/639c7b28e0e0e337094ada5a8770e5ad840d4135/src/redux-middleware/pushQueue.ts#L141)

**Comment by raineorshine** [comment]
> A `pass` here refers to each `existingThoughtMove` operation (`sync`) that would move all the visible, non-conflicting source thoughts to the destination.
> Each pass is followed by a `flushMoves` operation (`async`) where we load the pending source/descendant thoughts (if any) and run the pass again (if any new thoughts were loaded in the flushMoves, they get moved. Otherwise, the ranks of the previously moved thoughts are fixed).
> I hope that explains.

Thank you for clarifying.

You'll need to find a way to do it in two passes. O(depth) passes of a throttled middleware which is already slow is not a viable option.

> Yes, we can calculate the source depth after pulling the source
> But there might be cases when we don't need to pull the source context at all (if it's already loaded). So we'd have to introduce another value in the [PushBatch](https://github.com/cybersemics/em/blob/354c6f32b2ea0ad02c480b36a881c88a5436f2b2/src/util/initialState.ts#L25) to allow passing the `depth` of the source from `ETM` to `flushMoves`, which'd be used at the time of [loading destination thoughts](https://github.com/cybersemics/em/blob/639c7b28e0e0e337094ada5a8770e5ad840d4135/src/redux-middleware/pushQueue.ts#L141)

Yeah, unfortunate but it seems necessary. It's more efficient than re-traversing the state.
