### ISSUE TITLE
HTML not rendered in alert

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1072]
## Steps to Reproduce

- a
- b

1. Make `b` bold
2. Drag `b` into `a`

## Current Behavior

Alert: `”<b>b</b>“ moved to “a”`

## Expected Behavior

HTML in thoughts should be decoded and rendered as HTML in alerts. 

Alert: ”**b**“ moved to “a”

**Comment by onurpolattimur** [comment]
What is the expected behaviour if length of the bold text is greater than THOUGHT_ELLIPSIZED_CHARS which is currently 16?

For example; 
- **Lorem Ipsum is simply dummy text of the printing and typesetting industry. **

The thought's value is wrapped up `<b> ` tag, but we ellipsize the value before showing alert. In this situation there will be opening tag at the head of the ellipsized message and no closing tag at the end of the ellipsized message. So the full text of the alert will be bold.

https://github.com/cybersemics/em/blob/dcc557e8646ae484c70accce7384a8e40c3df8eb/src/components/Subthoughts.tsx#L223

**Comment by raineorshine** [comment]
Good catch! We would want to close all the open tags after ellipsizing so that they don't leak into the rest of the alert. I think `ellipsize` itself is the right place for that.
