### ISSUE TITLE
Toolbar button click animation

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1110]
This will make user actions more visible during mobile screen captures. 

- On touchstart/mousedown: animate toolbar button down a few pixels
- On touchend/mouseup: animate toolbar button back up

**Comment by onurpolattimur** [comment]
Adding background may be better especially for mobile. Even we move down 10px the button when I touch down the toolbar item I can not see still this item because my finger will be on the button.

![image](https://user-images.githubusercontent.com/23136437/116757083-0bdd7f80-aa16-11eb-824a-cd2dde088168.png)

**Comment by raineorshine** [comment]
> If the purpose of this feature is to make the user action more visible when we capture the screen, it is ok to move the button down.

Yes, this is the main purpose.

> Even we move down 10px the button when I touch down the toolbar item, I can not see still this item because my finger will be on the button.

Yeah, it will be pretty hidden for the mobile user.

> So we can add background.

What do you mean?

**Comment by onurpolattimur** [comment]
Okay good. I have pushed the changes with #1116. Now, we move down the button 10px, it is really useful while capturing the screen.

I mean, if we also want to give feedback to users while pressing the button, we can add background to the toolbar item. Because the user's finger will be on the button, the user will not see that the button is going down.

**Comment by raineorshine** [comment]
Do you mean set a background color on the toolbar item as they press it?
Wouldn't that be covered by their finger too?

**Comment by onurpolattimur** [comment]
> Do you mean set a background color on the toolbar item as they press it?
> Wouldn't that be covered by their finger too?

Yes, but the user can see the place the top of the button as you can see in my screenshot that I have posted before.

**Comment by raineorshine** [comment]
True. I don't think a solid background color is the aesthetic I want though. I'll keep this in mind but for now it's low priority so I think we should come back to it later.
