### ISSUE TITLE
Font Size improvements

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1152]
Make the following improvements to the font size links in the bottom left of the footer:

- Add more space in between A(+) and A (-) to make them easier to tap on mobile. Use `em` units so it scales correctly.  
- When changing the font size, dispatch an `alert` that says “Font Size: X” that autocloses in 2 seconds. 
- When changing the font size, scroll to the bottom of the screen. This prevents the scroll position from moving around when the font size changes (only visible when there are a large number of thoughts in the root).

**Comment by ruchijn** [comment]
@raineorshine I have implemented a custom alert because browser alert cannot be controlled to auto close. Before I go any further, wanted to check in with you if this is fine. 

![font_enhancements](https://user-images.githubusercontent.com/18288628/119232207-56708a00-baf2-11eb-961a-6590a37f7ace.gif)

**Comment by raineorshine** [comment]
Thanks for checking in. When I say "dispatch an `alert`" I am referring to the `alert` action-creator: https://github.com/cybersemics/em/blob/dev/src/action-creators/alert.ts. 

I assumed you would know that the word "dispatch" referred to the Redux mechanism but I hadn't made that explicit so my apologies.

**Comment by ruchijn** [comment]
I saw that one. But then I didn't spend enough time exploring it. I should have done that though.
