### ISSUE TITLE
Invitation Code System

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1192]
Implement a referral system that allows users to invite three other users to the app and restricts signups to those with an invitation, as described below.

## NavBar

Render a gift icon to the left of the feedback icon in the bottom right.

Use [this SVG](https://thenounproject.com/search/?q=gift&i=2221484) from the noun project and credit the creator with the [other icon credits](https://github.com/cybersemics/em/blob/dev/src/components/ModalHelp.tsx#L186-L198) on the help modal.

![image](https://user-images.githubusercontent.com/750276/119882128-48a07780-beeb-11eb-9696-41ea8b0aef32.png)

## Gift Modal

- When the gift icon in the NavBar is clicked, open the Gift Modal (see below)
- When a gift icon or masked code input is clicked:
  - unmask the input and display a signup url containing a new invitation code
    - `${window.location.origin}/signup?code=${code}`
  - codes stay unmasked after they are generated
  - add a check mark to the right of a code when it is used

## Signup

- show the signup screen when the app loads
- show a message if the invitation code is missing
  - "em is currently in beta. Please join the waitlist, or find a friendly person who can offer you an invite to gain access immediately."
- show a message if the invitation code does not exist in the database
    - "Invalid invitation code"
- show a message if the invitation code has already been used
    - "This invitation code has already been used"
- when a user signs up, update the invites object with `{ used: ${Date.now(), usedBy: ${user.uid} }`

![em-gift-modal](https://user-images.githubusercontent.com/750276/119891517-4a236d00-bef6-11eb-914a-3ca8769481c4.png)

## Implementation

Happy to discuss and open to suggestions!

- When a gift icon or masked code input is clicked:
  - retrieve an invitation code from the Firebase function
- Write a Firebase function that generates an invitation code
  - throw an error if the user is not authenticated
  - throw an error if the user has already generated their three invites
  - create the invitation code with `uuid.v4().slice(0, 8)`
  - store the invite object in Firebase at `/invites/${code}`
    - `{ created: Date.now(), createdBy: user.uid }`
  - store the code in the user object at `/users/${user.uid}/invites/${code}` with value `true`
  - return the newly created invitation code
- When a user signs up, update the invites object with `{ used: ${Date.now(), usedBy: ${user.uid} }`

**Comment by ruchijn** [comment]
I am in process of integrating it with DB. This is mid-point check in so that you can have a look at UI behaviour. Please let me know if this makes sense. 

Mobile:
![referral_system_ui_mobile](https://user-images.githubusercontent.com/18288628/120947020-6f8d5380-c70c-11eb-8569-c7adf1a60b48.gif)

Tablet:
![referral_system_ui_tablet](https://user-images.githubusercontent.com/18288628/120947025-72884400-c70c-11eb-899b-263dd4fbeb1c.gif)

Desktop:
![referral_system_ui_desktop](https://user-images.githubusercontent.com/18288628/120947029-76b46180-c70c-11eb-9289-a118022a1f8b.gif)

**Comment by raineorshine** [comment]
Looks great!

One thing: Once a code is unmasked, it should stay unmasked forever.

**Comment by raineorshine** [comment]
Feel free to open a draft PR

**Comment by shresthabijay** [comment]
@raineorshine @ruchijn I have the following things in mind. I think these are necessary for this feature to function properly.

-  We need a firebase rule to prevent users to create more than three invites.

- Do not make `/invites` firebase database path directly accessible. Only allow reading and updating to the particular invite if a user has its uuid. 

- Firebase cannot restrict users from signing up. Invitation system only works if we allow signed-up users with redeemed invites to access the resources. My plan is to create a `/allowed_users` path and add the users to it using a rest API that takes the user id and invite code. This API uses firebase admin to check if the invitation is legit and adds the user uuid to allowed users. It is necessary for it to be a rest API because we cannot allow users to directly access `/invites` path. After that we can add a firebase rule that the user can only have access to the resources if he is an allowed user.

- Do not allow users to use the app unless they sign up and we check if they are invited. Only for production-ready app where invitations are necessary. For development, we can just allow it.

Please let me know your views on this. Thanks!

**Comment by ruchijn** [comment]
> * Do not allow users to use the app unless they sign up and we check if they are invited. Only for production-ready app where invitations are necessary. For development, we can just allow it. - This is what I am working on next. IN production, the default screen will be login but in development, I will be providing an option for us to work without authenticating.
