### ISSUE TITLE
cursorPrev to pinned thought should not collapse and expand

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1212]
## Steps to Reproduce

```js
- a
  - b
    - =pin
      - true
    - c
  - d
```

1. Set the cursor on `a/d`
2. Activate `cursorPrev` (<kbd>cmd</kbd> + <kbd>up</kbd>)

## Current Behavior

`a/b` collapses for a moment and then re-expands

## Expected Behavior

When `cursorPrev` moves to a pinned thought, it should not collapse and expand since the thought is already expanded.

The same should be done for `cursorNext` in the other direction.

![Screen Recording 2021-06-02 at 6 25 13 AM mov](https://user-images.githubusercontent.com/750276/120465136-e0beb680-c35a-11eb-9b94-1ca95c2382a2.gif)

**Comment by shresthabijay** [comment]
@raineorshine The issue is caused by global suppressExpansion. 

https://github.com/cybersemics/em/blob/a8b5ed6881797e78ff05a238f5c07f87307f6eb8/src/selectors/expandThoughts.ts#L55-L60

On `cursorPrev` and `cursorNext` `suppressExpansion` is active for about 100ms. Since `expandThoughts` just returns an empty  `expanded` if `suppressExpansion` is true, it causes pinned thoughts to collapse and then reappear again after suppression duration.

We should allow expansion of pinned children even if the `supressExpansion` is active. How do you think we should approach this?

**Comment by raineorshine** [comment]
I'd love to hear your suggestion, then I can provide feedback. Where would make the most sense to put this? What code should know about these details (and, implied, what code shouldn't)?
