### ISSUE TITLE
Short swipe right causes cursorBack and touch

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1268]
Tested on iOS Safari. 

## Steps to Reproduce

```js
- a
  - b
```

1. Set the cursor on `a/b` with the keyboard down. 
2. Perform a very short swipe directly on top of `b` or to the right. If it is too short it will just enter edit mode. If it is too long it will just activate `cursorBack`. 

## Current Behavior

The cursor rapidly moves from `b` to `a` and back again. 

In this video I reproduce it twice in a row. The only touch I perform is two short swipe rights. 

https://user-images.githubusercontent.com/750276/121792996-15d3d000-cbc9-11eb-93fb-033ac6b3fcd2.mov

## Expected Behavior

The cursor should move back on swipe right.

**Comment by onurpolattimur** [comment]
@raineorshine, I couldn't reproduce the issue. Can you please draw a line on a screenshot to shows the swipe position and length?

**Comment by raineorshine** [comment]
Here is my best guess. It is just a tiny bit of a swipe to the right, slightly more than what registers as a click. I can reproduce it consistently, if I get the length right. 

My remote debugging in Safari is not working today otherwise I would get the exact number of pixels for you. 

![image](https://user-images.githubusercontent.com/750276/122475090-24880180-cf92-11eb-90ce-63e646980b69.jpeg)

**Comment by onurpolattimur** [comment]
I tried a lot but I couldn't reproduce the issue. 
I connected a trackpad to my iPhone to show the position and length of my touches and captured the screen.

https://user-images.githubusercontent.com/23136437/122636885-44373b00-d0f4-11eb-9a9f-cffe88a93960.MP4

**Comment by raineorshine** [comment]
Thanks for the screen capture. You don't appear to accidentally be entering edit mode, which tells me that your swipes are too long. Instead of starting with longer swipes and trying to shorten them, start with a right swipe that is so small that it triggers the click event that enters edit mode. Then increase the length by a few pixels to trigger the issue.

If you've done everything you can, no problem and I'll take it :).

**Comment by onurpolattimur** [comment]
Hi Raine, 
I reproduced the issue finally. Here is what I found so far.

`onMouseDown` event of Editable is triggered after `cursorBackShortcut` is executed. So it is like we are tapping thought 'B' while `cursorBack` is executed and so, the cursor goes back to 'B'. 

onMouseDown event is triggered but it shouldn't be triggered. For normal cases (not tiny swiping) it isn't triggered. I am not sure how we can handle this.
![image](https://user-images.githubusercontent.com/23136437/123151590-4985e400-d46c-11eb-88ee-8221d49588e1.png)

**Comment by raineorshine** [comment]
Glad you found it!

If I understand correctly, the gesture is executed so quickly that `touchend` fires before `mousedown`. `globals.touching` is false by the time `mousedown` is activated. Thus, `onTap` does not short circuit the call to `setCursorOnThought`.

I have two suggestions you could try:

1. Have `MultiGesture` stop propagation of `mousedown` after a successful gesture.
2. Have `TouchMonitor` wait until the next tick before setting `globals.touching` back to false.

**Comment by onurpolattimur** [comment]
1- I don't think the onMouseDown of Editable is been triggering because of the event bubbling. The reason why onMouseDown or onTouchEnd event triggered is we are activating the `back` gesture on an Editable element. Also, there is no onMouseDown event handler in the MultiGesture component, so there is no event to propagate in MultiGesture.

2- I tried, nothing changed.

In a normal scenario (not short swiping) the `onMouseDown` event is not triggered after `onTouchEnd` event. I wondered why the onMouseDown event is been triggering when we perform short swipe and I created a simple example. So I saw the same result in the simple app. When we perform a very short swipe on an element, `onTouchEnd` and `onMouseDown` events are triggered respectively. But when we perform a normal swipe on an element only `onTouchEnd` is triggered. You can test it on ios safari using the preview URL below. In case your remote debugging is not working still, I am writing event types into div to see which event is triggered.
Source code: https://codesandbox.io/s/beautiful-blackwell-3v8fq?file=/src/App.js
Preview URL: https://3v8fq.csb.app/

As a solution, we can call event.preventDefault in onTap if the current event is `touchEnd` and ` global.touching` is true.  This will prevent triggering the `onMouseDown` event after `touchEnd` event but I am not sure whether it will break some other things. I tried and run our ios, mobile, and desktop tests and I couldn't see any problem. What do you think? Does it make sense to you?

It is a little complicated case I hope I could explain it clearly.

**Comment by raineorshine** [comment]
I had to read that a few times and do some console.logs to make sense of it all. It sounds right though, and the solution you suggested works well. Thanks for your explanation. I'll merge the PR I made and keep an eye out for regressions as I am using the app. If we get a regression it will be easy to track to this commit.

A few brief notes during my debugging to provide a record for future selves:

- useEffect setSelection is not triggered
- onFocus is not triggered
- clickOnEmptySpace is not called

Fixing the issue leaves an awkward space in between a click and a gesture where nothing happens. I decreased (nearly eliminated) the gesture [threshold](https://github.com/cybersemics/em/blob/dev/src/components/MultiGesture.tsx#L189-L190) so that we still get a valid gesture with a tiny swipe. We can always revert only 78ca6f8090eedd07c7a95b2ec1dc331e260e26d8 if the extra gesture sensitivity causes any problems.
