### ISSUE TITLE
subcategorizeAll deletes children with empty thought

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1391]
## Steps to Reproduce

```js
- a
  - b
  - c
  - [empty]
```

Activate `subcategorizeAll` on any child of `a`. 

## Current Behavior

`b` and `c` are deleted

## Expected Behavior

`b`, `c`, and the sibling empty thought should be indented under the new empty thought:

```js
-  a
  - [empty]
    - b
    - c
    - [empty]
```

**Comment by shresthabijay** [comment]
We cannot have duplicate thoughts in the same context but we can create two empty thoughts. They are duplicates too. Since we uniquely identify thoughts using `context`, it will cause duplication problems when two empty thoughts are there in same context.

To understand the problem we need to see how `subCategorize` works:

First creates new empty thought in the given context. This creates two empty thoughts in the context as there is already one empty thought.

```
- a
 - [empty]
 - b
 - c
 - [empty]
```

After that, all the other children are moved inside the empty thought.  After `b` and `c` is copied it looks something like this.

```
- a
 - [empty]
  - b
  - c
 - [empty]
  - b
  - c
```

**Comment by shresthabijay** [comment]
This will be solved by #1349 eventually. For now the easiest solution would be to create a new thought with some random uuid value and then move the children. Then rename the thought back to empty value.

**Comment by raineorshine** [comment]
Thanks for the explanation. We can hold for #1349.

The problem actually appears to be in `moveThought`. `subCategorizeAll` passes the correct `Paths`:

![image](https://user-images.githubusercontent.com/750276/129824523-119705d3-82b9-428f-9d2d-82efb8f10636.png)

**Comment by raineorshine** [comment]
Fixed
