### ISSUE TITLE
Superscript not rendered on load

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1419]
## Steps to Reproduce

```
- a
  - b
- b
``` 

1. Set the cursor to null
2. Refresh the page

## Current Behavior

`b` has no superscript until something causes a reload. 

## Expected Behavior

`b` should have a superscript of 2.

**Comment by ruchijn** [comment]
In `pull.ts` thoughts fetching is async await at https://github.com/cybersemics/em/blob/dev/src/action-creators/pull.ts#L68. 

By the time `state` is being read at https://github.com/cybersemics/em/blob/dev/src/components/ThoughtAnnotation.tsx#L127, all the thoughts haven't been fetched. And hence we see the issue. 

If we make `ThoughtAnnotation` to read `state` again whenever `thoughts` gets updated, the issue is fixed and it works as expected. 
```
const state = useRef(store.getState())
  useEffect(() => {
    state.current = store.getState()
  }, [thoughts])
```

Please let me know if there was a reason behind not making `ThoughtAnnotation` dependent on `thoughts`. 

I ran unit tests locally and it was all good.
