### ISSUE TITLE
getDescendantThoughts: Cannot get parent for some ids of [ROOT]

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1456]
I am getting an error in the console on a fresh load: `getDescendantThoughts: Cannot get parent for some ids.  ['__ROOT__']  []`. 

At `getDescendantThoughts.ts:64`.

**Comment by shresthabijay** [comment]
@raineorshine This error warning in the `getDescendantThoughts` is there in case we try to pull things that are not available in the persistence layer. It put it there during the migration phase, so that we could see if anything is going wrong with pulling. 

Incase of fresh load. The `contextIndex` entry for `__ROOT__` is available in the state, but we don't have it yet on the persistence layer. So on trying to pull the thought for id `__ROOT__` it shows this error. 

I think we can either change the log to be a warning instead of an error because it is possible to query thoughts that are not available in the DB yet. Or we can remove logging altogether. What do you think ?

**Comment by shresthabijay** [comment]
> I don't think we can properly distinguish between true errors and false positives, since `__ROOT__` is not the only source of the problem: loading a url with an id that has been deleted would result in the same situation for an arbitrary thought. Therefore, I would remove the check.
> 
> It's valid for `getDescendantThoughts` to yield zero thoughts, which should be anticipated upstream anyway.

I agree with you here. We can remove this check.
