### ISSUE TITLE
Merge thoughts not working

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1465]
## Steps to Reproduce

``` 
- a
  - b
- c
  - a
    - d
``` 

Move `c/a` up a level

## Current Behavior

``` 

- a
  - b
- c
- a
  - b
``` 

## Expected Behavior

Thoughts should be merged recursively. Must work with pending destination thoughts as before. 

``` 
- a
  - b
  - d
- c
```

**Comment by shresthabijay** [comment]
## Merge

Incase of merge with no duplicate children merge happens without needing to pull other descendants.

## Incase of nested duplicate children and pending thoughts.

Let's say we have the following thoughts in the tree

- a
	- b
		- c (not loaded)
			- n
		- f
	- d
- k
	- a
		- b
			- c
				- m
			- g
		- e

**When `k/a` is moved to the home context.**
- `k/a` is merged to `a`. 
- Finds duplicate children with value `b`.
- Both `a/b` and `k/a/b` is loaded.
- `k/a/b` is merged to `a/b`.
- Finds duplicate children with value `c`.
- `a/b/c` is not loaded yet. So we cannot confirm there are duplicates when `k/a/b/c` is merged into `a/b/c`.
- Return the updates as 
```js
	const updates = {
		'idOfA': {	
			children: ['idOfA/B', 'idOfA/D', 'idOfK/A/E']
		},
		'idOfK/A': null,
		'idOFK/A/E': {
			parentId: 'idOfA'
		},
		'idOfA/B': {
			children: ['idOfA/B/C', 'idOfA/B/F', 'idOfK/A/B/G']
		},
		'idOfK/A/B': null,
		'idOfK/A/B/G': {
			parentId: 'idOfA/B' 
		}
	}
```

- Add `{ mergeTargetId: 'idOfA/B/C', mergeSourceId: 'idOFK/A/B/C' }` as entry to `pendingMerges`. `pendingMerges` should be persisted into the data layer to make sure we can resolve the merges later if the application is closed.
- We can see that thought at `k/a/b/c` is not deleted yet. But is now an orpahaned thought until the `pendingMerges` is deleted.
- In pull priortize `pendingMerges` . May be with a maxDepth of about 2 or 3.
- Perform `moveThought` on the `pendingMerges`. 
- Change `moveThoughts` to use thought id's instead of the path. I think this is necessary because with independent editing we need low level operations to not be dependent on the context (Unless opertation `move` behaves differently based on some ancestors. We can discuss about this). This makes it possible for orphaned thoughts to exist in the tree. We can always verify these orhaphaned thoughts using `pendingMerges` which is always persisted.
	
**(Local) In case when app is closed and the merges are not resloved.**
	
- Since we always have `pendingMerges` persisted on the data layer. We can resume it by pulling `pendingMerges` into the app state from the indexed DB.

**(Remote) With multiple devices active.**

- Pending merges should be resolved only on one of the active devices. So `pendingMerges` should be persisted on the remote data layer too.
- Only one of the online devices should perform the merging. The device that initiates the merging should be prioritized.
- If the device that initiated the merging goes offline. One of the devices should pick up the responsibility of merging. It is because pending merges create orphaned thoughts and it would not be resolved if the initiating device goes offline and doesn't come back online.
- For this, we need to have some mechanism to track the devices and round-robin the pending merge responsibility. We need to discuss this.

@raineorshine These are my thoughts on merging thoughts. Please let me know what you think about it.

**Comment by raineorshine** [comment]
Thanks for the thoughtful proposal! 

> * `a/b/c` is not loaded yet. So we cannot confirm there are duplicates when `k/a/b/c` is merged into `a/b/c`.

Yes, exactly. I agree with the opportunistic update up to the pending merge point.

> * We can see that thought at `k/a/b/c` is not deleted yet. But is now an orpahaned thought until the `pendingMerges` is deleted.

I would like to avoid orphaned thoughts since data integrity issues are so pernicious. Luckily, there is a divide-and-conquer solution that never leaves the thoughts in an invalid state.

Instead of leaving `idOfK/A/B/C/M` in the nonexistent `k/a/b/c` context, we immediately move it to `a/b/c` where it belongs. This leaves it in a valid state, with a potential merge conflict when the target is pulled. There is some added complexity handling these pull conflicts, but I think it is better than the risk of persisting data integrity issues. Since thoughts are represented by unique ids, we just need to union the children of the pending merge point once the pull completes. We may even have some logic in place that handles this already. I'm not sure what happens currently when a `pull` target has children already.

We can have a `pendingMerges` data structure as you suggest, so that merging can be resumed if it is interrupted.

> (Remote) With multiple devices active.

Wouldn't the server end up in the same state if multiple clients performed the merge conflict independently?

**Comment by shresthabijay** [comment]
> Wouldn't the server end up in the same state if multiple clients performed the merge conflict independently?

Yes, it will. However, the different clients may be navigating different parts of the tree. They may not have loaded the thoughts necessary for the merge. All the active clients would have to load all the thoughts necessary and merge the same thing. Even if the merge initiating client is active. All the other clients would have to merge it themselves too.

For simplicity, we can go with all clients merging too. But there would still be room for improvement here.

**Comment by shresthabijay** [comment]
> Instead of leaving `idOfK/A/B/C/M` in the nonexistent `k/a/b/c` context, we immediately move it to `a/b/c` where it belongs.

I agree on this.

**Comment by raineorshine** [comment]
> > Wouldn't the server end up in the same state if multiple clients performed the merge conflict independently?
> 
> Yes, it will. However, the different clients may be navigating different parts of the tree. They may not have loaded the thoughts necessary for the merge. All the active clients would have to load all the thoughts necessary and merge the same thing. Even if the merge initiating client is active. All the other clients would have to merge it themselves too.

If Client B is navigating a different part of the tree, then we shouldn't have to do anything. Client A will merge and push to the server, and Client B will just pull if it navigates to that thought.

If Client B is navigating the same part of the tree, then it will get the update from the server after Client A has pushed. It may see `pendingMerges` and try to merge itself, but I am hoping redundant merges will be idempotent.

> > I'm not sure what happens currently when a `pull` target has children already. We may be able to flag the local children to be kept rather than replaced.
> 
> We can use `pull` to prioritize the `pendingMerges` thoughts and then actually iterate over the children to find the merge conflict at one level. If we find then we repeat the same thing over.

Can you expand on this? When do we iterate over the children, and when do we repeat?

We should confirm what happens currently when a context has existing children when a pull completes. I vaguely remembering handling this so that the children are combined, but I'm not sure.

**Comment by shresthabijay** [comment]
> If Client B is navigating a different part of the tree, then we shouldn't have to do anything. Client A will merge and push to the server, and Client B will just pull if it navigates to that thought.

But when do we delete the entry from `pendingMerges` ? If one of the clients merges, then should we delete it from the `pendingMerges` ?

**Comment by raineorshine** [comment]
Oh, good point. The clients will see `pendingMerge` and try to complete the merge even if they do not have that context loaded into memory.

The `pendingMerges` entry should be deleted atomically when the merge is executed.

**Comment by shresthabijay** [comment]
> We should confirm what happens currently when a context has existing children when a pull completes. I vaguely remember handling this so that the children are combined, but I'm not sure.

I believe `pending` is the property that denotes the children of the current thought that has not been pulled yet. So when I say `a/b/c` has not been loaded, it means its children have not been loaded yet.

So `k/a/b/c` into `a/b/c` cannot be merged because we have not loaded the children's thoughts related to `a/b/c`. 

These are the two approaches that I can think of without having orphaned thoughts in the state.

## Merge the conflicted thoughts and then later resolve the conflicts with the children.

- Even though the children's thoughts have not been loaded for `a/b/c`, we can merge the children of `k/a/b/c` to it. That means there is possibility of conflicts once thoughts are loaded and resolved.

- We delete thought related to `k/a/b/c`. The indices updates would look like this.

```js
const updates = {
		'idOfA': {	
			children: ['idOfA/B', 'idOfA/D', 'idOfK/A/E']
		},
		'idOfK/A': null,
		'idOFK/A/E': {
			parentId: 'idOfA'
		},
		'idOfA/B': {
			children: ['idOfA/B/C', 'idOfA/B/F', 'idOfK/A/B/G']
		},
		'idOfK/A/B': null,
		'idOfK/A/B/G': {
			parentId: 'idOfA/B' 
		},
		'idOfA/B/C': {
		   children: ['idOfA/B/C/N', 'idOfK/A/B/C/M']
		},
		'idOfK/A/B/C': null,
		// Note: We cannot update thought `idOfK/A/B/C/M` to have parent id of `idOfA/B/C` instead of `idOfK/A/B/C` because it has not been loaded yet.
	}
```

- One important thing to note here is that we cannot update thought `idOfK/A/B/C/M` to have parent id of `idOfA/B/C` instead of `idOfK/A/B/C` because it has not been loaded yet. It can only resolve it once it has been loaded.

-  `pendingMerges` will slightly change to have only the id of the thought that might possibly have the conflicting children. In this case thought id related to context `a/b/c`.

```js
const pendingMerges = [...prevMerges, 'idOfA/B/C']
```

- We pull the thoughts related to the `pendingMerges`, then first update the `parentId` of the children that don't match. Then check for the conflicts. If there are no conflicts we can stop there. If there are we have to merge those which are conflicted.

## Deliberately have a conflicting thought.

- We have two conflicting `k/a/b/c` and `a/b/c` thoughts that need to be as children of `a/b/c`.
- Instead of merging the possible conflicted children's we move `k/a/b/c` into `a/b` and tag it as a `pendingMerge` with `a/b/c`.
- We tag thought related to `k/a/b/c` as `pendingMerge`
- We have following updates.

```js
const updates = {
		'idOfA': {	
			children: ['idOfA/B', 'idOfA/D', 'idOfK/A/E']
		},
		'idOfK/A': null,
		'idOFK/A/E': {
			parentId: 'idOfA'
		},
		'idOfA/B': {
                        // Note: We have conflicting children here.
			children: ['idOfA/B/C', 'idOfA/B/F', 'idOfK/A/B/G', 'idOfK/A/B/C']
		},
		'idOfK/A/B': null,
		'idOfK/A/B/G': {
			parentId: 'idOfA/B' 
		},
                'idOfK/A/B/C': {
			parentId: 'idOfA/B' ,
                         // Note: We tag it so that we can filter it out.
                         pendingMerge: true
		},
	}
```

- We add entry to `pendingMerge` as :

  ```js
  const pendingMerges = [{ mergeTargetId: 'idOfA/B/C', mergeSourceId: 'idOFK/A/B/C' }]
  ```
 
 - We persist these `pendingMerges`.
 - We always filter out conflicted thought out using `pendingMerge` property on `Parent`.
 - We pull the required `pendingMerges` thoughts and resolve it and then remove the tag from the conflicted thought.
 
 
These are both valid approaches that I can think of. However, I strongly prefer the second approach because of the following reasons:

- In both approaches, we won't have orphaned thoughts but in the case of the first approach, some children thought `parentId` would not be in sync until merges are resolved.

- In the first approach, we may or may not end up with the merge conflict once we have loaded the necessary thoughts. If there are no conflicts it's good. But in case of conflicts, it would be more complex to resolve it. With the second approach we deliberately have a conflicted thought in context, in order to keep the `parentId` of the children to be always in sync. We don't have orphaned thoughts too. We just have a conflicted thought that we know and marked, that will be resolved once the necessary thoughts are loaded. 

- As you can see we will always have an invalid state with both approaches. But I would rather have a conflicted thought that is known and marked instead of having a bunch of children whose `parentId` is out of sync.

@raineorshine  There are my thoughts on how to deal with the pending merges. Let me know your thoughts on this.

**Comment by raineorshine** [comment]
> * One important thing to note here is that we cannot update thought `idOfK/A/B/C/M` to have parent id of `idOfA/B/C` instead of `idOfK/A/B/C` because it has not been loaded yet. It can only resolve it once it has been loaded.

`idOfA/B/C` has been loaded, it's just pending. It seems like we can update thought `idOfK/A/B/C/M` to have parent id of `idOfA/B/C` instead of `idOfK/A/B/C`, unless I am mistaken.

If we used this approach, we would have to update the parent id, because the old parent `idOfK/A/B/C` no longer exists.

> * We have two conflicting `k/a/b/c` and `a/b/c` thoughts that need to be as children of `a/b/c`.
> * Instead of merging the possible conflicted children's we move `k/a/b/c` into `a/b` and tag it as a `pendingMerge` with `a/b/c`.
> * We tag thought related to `k/a/b/c` as `pendingMerge`

Yup, exactly. This leaves duplicate (unmerged) thoughts in `a/b`, but there are no orphaned thoughts.  Then after the pending thoughts are pulled the merge can continue.

> * We tag thought related to `k/a/b/c` as `pendingMerge`

By "tag" do you mean add it to `pendingMerge`, or something else? Just to clarify.

> ```js
> 		'idOfA/B': {
>                         // Note: We have conflicting children here.
> 			children: ['idOfA/B/C', 'idOfA/B/F', 'idOfK/A/B/G', 'idOfK/A/B/C']
> 		},
> ```

FYI Not that the array is used for ordering, but if we were to sort them by rank the source children would appear after the target children in order: `['idOfA/B/C', 'idOfA/B/F', 'idOfK/A/B/C', 'idOfK/A/B/G']`.

> * As you can see we will always have an invalid state with both approaches. But I would rather have a conflicted thought that is known and marked instead of having a bunch of children whose `parentId` is out of sync.

It's actually not an invalid state as long as there are no orphaned children. **em** supports duplicates, it has just been modified to avoid them for the user experience.

Yup, that sounds reasonable to me.
