### ISSUE TITLE
Importing mixed HTML with whitespace causes newline

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1573]
## Steps to Reproduce

```
a
<li>b</li>
```

## Current Behavior

Creates a thought `a\nb`

## Expected Behavior

Should create two thoughts:

- a
- b

## Note

For some reason, if you delete the thought and repeat the steps, it alternates between the correct behavior and incorrect behavior.

**Comment by karunkop** [comment]
## Cause of issue

There is a function called `parseBodyContent` in `textToHtml.ts` which checks for a regex expression for a `li` tag. From the reference I have found this:
> If the regex has the global flag set, test() will advance the [lastIndex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex) of the regex. A subsequent use of test() will start the search at the substring of str specified by [lastIndex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex) ([exec()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec) will also advance the [lastIndex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex) property). It is worth noting that the [lastIndex](https://developer.mozilla.org/en-US/docs/) will not reset when testing a different string.

Due to this alternating behavior is seen when pasted and deleted the particular html string. When regex expression test is true,  simply `content` is returned without stripping, hence a single thought is created as multi line.
