### ISSUE TITLE
[Mobile Safari] CopyOneDrop does nothing

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#1679]
Mobile Safari only

## Steps to Reproduce

1. Create a thought
2. Drag the thought to the copy icon that slides out from the right edge of the screen.

## Current Behavior

Nothing happens.

## Expected Behavior

Should copy the thought text to the clipboard just like on desktop.

## Notes

Copying to clipboard is done with [ClipboardJS](https://github.com/zenorocha/clipboard.js).  It works perfectly on mobile in the [ModalExport component](https://github.com/cybersemics/em/blob/2e71bb2cf1cc5d53cc03468d3188ba7a75d07d36/src/components/ModalExport.tsx#L343). Both ModalExport and CopyOneDrop use the `ClipboardJS` module to do the copying, but using different techniques. CopyOneDrop uses https://github.com/cybersemics/em/blob/dev/src/device/copy.ts which is supposed to mitigate the need for an existing element as the copy container.

See: 

- https://github.com/cybersemics/em/blob/dev/src/components/CopyOneDrop.tsx
- https://github.com/cybersemics/em/blob/dev/src/device/copy.ts

**Comment by ankitkarna99** [comment]
## Limitations
- `ClipboardJS` is working fine. The issue is that iOS doesn't allow anything to be copied without user-interaction i.e. literally real user clicking a button. Currently we have `ontouchend` as the event, which doesn't suffice Apple's requirements.

## Approaches I tried but didn't work
- Using the approach that is working: Append button to the dom, apply `ClipboardJS` to it and click it programmatically. This makes the ClipboardJS approach same as the `ModalExport` component.
- Tried selecting contents and executing `execCommand('copy')`. Only real (not simulated) copy commands are accepted for copy.
- Used `textarea` with `contentEditable` set to `true` and `readOnly` set to `false`, then used selection API to select and execute `execCommand('copy')`

**Comment by raineorshine** [comment]
Will have to settle for ExportDrop due to the above browser limitation. We could add an extra step to confirm the copy, but that would be the same number of steps as ExportDrop.
