### ISSUE TITLE
Fix ModalExport tests

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2130]
The ModalExport tests are currently being skipped due to a replication issue.

https://github.com/cybersemics/em/blob/5ffafd3a22beb062ff2b55b87115fe898aea7870/src/components/__tests__/ModalExport.ts

**Comment by mstrofbass** [comment]
@raineorshine this is ready to merge but I'd like you to take a quick look since I made two additional minor changes.

1. Removed an apparently extraneous space from a text node. Since browsers collapse these by default there was no visual impact of the extra space. I think removing it is the correct solution here but I want to make sure there's not something I don't know.
2. I swapped `findAllByText` to `getByTestId`. I'm not 100% sure what your philosophy is about how we should be finding elements but in this case the use of `findAllByText` is arguably problematic because we're effectively hardcoding the order in which elements appear on the screen. I think using `data-testid` is a better option but there are probably other options for how we might want prefer to do this.

https://github.com/cybersemics/em/pull/2660

**Comment by raineorshine** [comment]
> 1. Removed an apparently extraneous space from a text node. Since browsers collapse these by default there was no visual impact of the extra space. I think removing it is the correct solution here but I want to make sure there's not something I don't know.

Yes, looks like that was a mistake!

> 2\. I swapped `findAllByText` to `getByTestId`. I'm not 100% sure what your philosophy is about how we should be finding elements but in this case the use of `findAllByText` is arguably problematic because we're effectively hardcoding the order in which elements appear on the screen. I think using `data-testid` is a better option but there may be other ways that you prefer.

I'll follow your lead on this one. There are so many ways to find/locate/waitFor elements I honestly don't have a good methodology.
