### ISSUE TITLE
Fix pullQueue tests

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2139]
The pullQueue tests are currently being skipped due to a data provider issue.

https://github.com/cybersemics/em/blob/f68689f6471af07ba87db97cdd9b68bf42cdc910/src/redux-middleware/__tests__/pullQueue.ts

**Comment by mstrofbass** [comment]
Taking an initial stab at this and my first observation is that we don't update `thoughtDocs` during the replication process during testing because we bail early:

https://github.com/cybersemics/em/blob/aba6ee6f022f898f7f9a48ed9da6a8b0b2407bbd/src/data-providers/yjs/thoughtspace.ts#L620-L641

This means, I think, that when we later try to call `getThoughtById` it returns null because the `thoughtDocs` map is empty. 

We update `thoughtDocs` later on in `replicateChildren`:

https://github.com/cybersemics/em/blob/aba6ee6f022f898f7f9a48ed9da6a8b0b2407bbd/src/data-providers/yjs/thoughtspace.ts#L687

**Comment by mstrofbass** [comment]
Copying the code from line #687 breaks all the calls to `cleanupTestApp` but seems to fix the first failure in the first test.

I'm not familiar enough with the architecture and `thoughtspace` is fairly complex so I'm not confident in the correct solution here.

**Comment by raineorshine** [comment]
Using git blame I can see that `import.meta.env.MODE === 'test'` was added due to a `TransactionInactiveError` coming out of fake-indexeddb. It will be necessary to remove that condition so that the thoughtspace can run normally during the tests. Then you can track down any errors from from the mocked IndexedDB.

8e5797e1f30cf1ba8a2a32398aba9be1ca9b9a95

Let me know if you have any questions about the data flow or persistence layer.

**Comment by mstrofbass** [comment]
Perfect, thank you! I'll run down that path and see what I can figure out.
