### ISSUE TITLE
Fix pushQueue tests

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2140]
The pushQueue tests are currently being skipped due to a data provider issue.

https://github.com/cybersemics/em/blob/f68689f6471af07ba87db97cdd9b68bf42cdc910/src/redux-middleware/__tests__/pushQueue.ts

**Comment by mstrofbass** [comment]
@raineorshine can you take a look at this test for me? It was commented out like two years ago so there have been some significant changes and I'm not familiar enough with the backend to know if this is testing the correct functionality anymore.

If it is, I'll keep debugging but I didn't want to spend a lot of time debugging the test if it doesn't actually reflect the expected behavior any longer. 

https://github.com/cybersemics/em/pull/2661

**Comment by mstrofbass** [comment]
I think it makes sense to add the `skip` back to the test but then merge the changes.

Do you have an issue created for the broken behavior? If so, I'll add it to a comment.

**Comment by raineorshine** [comment]
Yes, thanks I reopened #1074.

**Comment by mstrofbass** [comment]
I think we should close this since we won't be fixing the underlying problem for the last test soon.

We need to make sure to the last test is unskipped/fixed once #1074 is fixed. Not sure how best to track this dependency.

**Comment by raineorshine** [comment]
Added to #1074. Thanks.
