### ISSUE TITLE
Fix undo-redo tests

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2145]
Two undo-redo tests are currently broken and being skipped.

https://github.com/cybersemics/em/blob/f68689f6471af07ba87db97cdd9b68bf42cdc910/src/shortcuts/__tests__/undo-redo.ts#L188-L245

**Comment by mstrofbass** [comment]
@trevinhofmann @raineorshine It appears that all tests that rely on calling `initialize()` are skipped; I assume because they are failing. I'm still getting up to speed on the architecture, so I apologize if the following comments are dumb.

My initial thought is that any test that requires a call to `initialize()` is not appropriate as a test at this level (non-e2e; whether unit, integration, functional, or whatever these are being called). IMO given the complexities in initializing a full application, doing so multiple times in this context will tend to cause weirdness in the tests (particularly if `yjs` isn't being mocked). My recommendation would be exercise the store using a mock store as done in other tests (e.g., in the preceding test [here](https://github.com/cybersemics/em/blob/ae469cd229c7496a06eb8e9db53b604bf96b144d/src/shortcuts/__tests__/undo-redo.ts#L156-L176)) and move any test that requires calling `initialize` or simulating a page refresh into the `e2e` tests.

Obv this may not be possible and I'm probably missing a lot of context here but I wanted to go ahead and float the idea before spending to much time trying to fix whatever weirdness is going on here.

I will note that the discussion about using fake timers with db calls [here](https://github.com/cybersemics/em/issues/919#issuecomment-739135971) makes me worried that this problem isn't easily solvable, another reason I wanted to float the alternative idea before spending too much time on this.

**Comment by raineorshine** [comment]
Hey! Great question. 

The main issue with moving these tests to puppeteer is that puppeteer is extremely slow by comparison, by an order of magnitude. In my experience this has a big impact on developer experience and significantly slows refactors. We other tasks that are devoted to speeding up the puppeteer tests. I don't want to add to the problem. 

The most important mocking for these tests is `fake-indexeddb`. YJS is synchronous and in-memory, so it shouldn't need to be mocked. We're actually migrating from YJS to a custom SQLite db layer. My concern is that if we don't resolve the timer issues with the current implementation, then we'll run into the same issue with the next implementation. Having working unit tests at the persistence level (without the overhead of a browser instance) will be a huge asset when it comes time to test the new SQLite implementation. SQLite will require a new mock, but the async communication with the db and all the tests cases for persisting thoughts, undo history, etc will be known to work going in. 

If there are fundamental issues with test timers that prevent mocking the async db operations I'm willing to consider other approaches, but it's worth it for us to thoroughly investigate the problem and better understand what those fundamental limitations are before pivoting. Bijay's research on test timers is a few years old now, and there may very well have been some critical bug fixes or new strategies for mocking async operations.
