### ISSUE TITLE
Refactor puppeteer helpers to use global browser page

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2363]
The puppeteer helpers were designed to avoid the use of global variables. To access the browser page, they used a convoluted process of currying the page object on setup. 

https://github.com/cybersemics/em/blob/main/src/e2e/puppeteer/helpers/index.ts

In practice, this offers little benefit. It adds complexity to understanding and using helpers, as well as friction adding new helpers. 

While the principle of decoupling tests from puppeteer specifics is good, the helpers themselves should be able to access the global browser object as needed. This will result in a simpler and easier-to-understand design. 

- Refactor all the puppeteer helpers to use the global browser object.
- Remove the helper index and import helpers directly in tests.

**Comment by mstrofbass** [comment]
@raineorshine looking into this and have some confusion.

My understanding of how this currently works is: Each helper requires a singular `page` object. This `page` object is created by the `setup` function and returned to the caller, which then creates a partial helper function with the `page` object applied. 

However, the `global.browser` object does not have a singular `page` object. Instead, it has a `pages()` function that returns one or more pages. I'm logging out `global.browser.pages()` within the `paste` helper just for exploratory purposes and I'm getting multiple pages. 

I believe this is because, on startup, puppeteer automatically creates a page. Then, when we call `setup`, we (1) create a new browser context and (2) call `newPage()` on the new context. This second call creates a second page and the global.browser object does not appear to have a way to differentiate them.

As such, I'm not sure what the best way to refactor this.

Based on my review, it looks like `setup` is required and is called when the `index` is loaded. My inclination (based on my limited understanding of the architecture at this point) would be to move the `beforeEach`  and `afterEach` into the individual test files, have them set the page object in the test file itself, then pass the page object to the helper functions. This obviously means that we can't remove the `page` parameter from the helper functions but unless there's some way to identify the actual target page then I'm not sure what other solution there is.

**Comment by mstrofbass** [comment]
A rough example from `caret.ts` would look like this:

```javascript
import { KnownDevices, Page } from 'puppeteer'
import helpers from '../helpers'
import setup from '../helpers/setup';
import paste from '../helpers/paste';
import clickThought from '../helpers/clickThought';
import waitForEditable from '../helpers/waitForEditable';
import click from '../helpers/click';
import press from '../helpers/press';
import getSelection from '../helpers/getSelection';
import clickBullet from '../helpers/clickBullet';
import waitUntil from '../helpers/waitUntil';

vi.setConfig({ testTimeout: 20000, hookTimeout: 20000 })

let page: Page = null as unknown as Page;

beforeEach(async () => {
  page = await setup()
}, 60000)

afterEach(async () => {
  if (page) {
    await page.close().catch(() => {
      // Ignore errors when closing the page.
    })
  }
})

describe('all platforms', () => {
  // TODO: Why is this failing?
  it.skip('caret should be at the beginning of thought after split on enter', async () => {
    const importText = `
    - puppeteer
      - web scraping
    - insomnia
      - rest api`
    await paste(page, importText)
    await clickThought(page, 'puppeteer')
    await clickThought(page, 'web scraping')

    const editableNodeHandle = await waitForEditable(page, 'web scraping')
    await click(page, editableNodeHandle, { offset: 3 })

    await press(page, 'Enter')

    const offset = await getSelection(page, ).focusOffset
    expect(offset).toBe(0)
  })
})
```

Not a huge fan of the redundancy but, again, not sure what the other options are here.

**Comment by raineorshine** [comment]
Thanks for questions. That would be an improvement, as it would remove the complexity and misdirection from the currying.

> My understanding of how this currently works is: Each helper requires a singular `page` object. This `page` object is created by the `setup` function and returned to the caller, which then creates a partial helper function with the `page` object applied.

Exactly. Overengineering at its best 😅

> However, the `global.browser` object does not have a singular `page` object. Instead, it has a `pages()` function that returns one or more pages. I'm logging out `global.browser.pages()` within the `paste` helper just for exploratory purposes and I'm getting multiple pages.

Fwiw, this is not intentional. All of the puppeteer examples use `context.newPage` which creates a second page, then the test is run on that new second page. None of our tests actually test multiple pages open at the same time, although I suppose it's possible in the future that we may want to test sharing data across tabs.

---

The ideal situation would be to have a global page object and not have to pass it to all the helpers. This could be stored on `global` or exported from a module that can be imported wherever it is needed. The only blocker I see with that is related to parallelization in the test environment. If parallel tests run in the same environment, we can't use a single global page object. However if `vitest` isolates each test, then the a global page object will work fine. I think this is probably worth confirming first, as our entire design depends on it.

**Comment by mstrofbass** [comment]
Vitest docs confirm that each _file_ runs in an isolated environment; initial experiments confirm this. The tests within the file are not isolated, but they currently run in sequence so there appear to be no problems. 

It's worth keeping in mind, however, that vitest has a (new?) `concurrent` feature that will let tests in the same file run concurrently, which will not function with this implementation. I will create a PR based on my changes so that you can review.

**Comment by raineorshine** [comment]
Yeah, I don't love the idea of precluding concurrent mode just for some syntax sugar.

What do you think? Is passing `page` to every helper an acceptable cost for easy-to-understand tests? Would love your opinion.

**Comment by mstrofbass** [comment]
For tests, I lean towards being very explicit and that usually requires a lot of repetition with the setup for each test. However, I don't think passing the `page` object is the type of explicitness that I lean towards because it technically makes it more clear but not in a super helpful way. 

With that in mind, perhaps the better solution is a secret third thing where instead of a `setup` function we have a function that wraps the page object and provides the helper methods? See below for a quick example. Obv this would be a lot easier if Puppeteer exposed a non-abstract version of the page class itself but it doesn't...so instead we have to use a wrapper function.

I think this is effectively a more clear, explicit version of what is there now. I would then import this into each file and either call it directly in each test or in a beforeEach. This way the person reading the test knows exactly what is going on for that specific test instead of having to navigate to a separate function.

```typescript
import chalk from 'chalk'
import { Browser, ConsoleMessage, Device, Page } from 'puppeteer'

import pressHelper from './press'
import pasteHelper from './paste'

// eslint-disable-next-line @typescript-eslint/no-namespace
declare module global {
  const browser: Browser
}

const DEFAULT_URL = process.env.CI ? 'https://172.17.0.1:2552' : 'https://host.docker.internal:2552';

async function puppeteer(url: string = DEFAULT_URL) {
  const browser = global.browser
  const context = await browser.createBrowserContext()
  const page: Page = await context.newPage()

  page.on('console', handleConsoleMessage);

  const acceptDialogs = () => page.on('dialog', async dialog => dialog.accept())
  const emulateDevice = async (emulatedDevice: Device) => await page.emulate(emulatedDevice);
  const skipTutorial = () => { skipTutorialOps(page) }
  const overridePermissions = async () => await context.overridePermissions(url.replace(/:\d+/, ''), ['clipboard-read', 'clipboard-write'])

  const press = pressHelper.bind(undefined, page)
  const paste = pasteHelper.bind(undefined, page)

  await page.goto(url)

  return {
    page,
    acceptDialogs,
    emulateDevice,
    skipTutorial,
    overridePermissions,
    press,
    paste,
  }
}
```

**Comment by mstrofbass** [comment]
FYI the code above is untested

**Comment by raineorshine** [comment]
Thanks! I like where this is going.

I asked @trevinhofmann for his opinion and he offered some great thoughts in a separate channel, as well as this [proof of concept](https://github.com/trevinhofmann/em/commit/e32e0d07498562d555dc46e5fd6e7a2f4086b0d3#diff-f9e74fbbe479cc54dcb6332fb02e8d114564846634e0d16f45d191a221bb5b03R4). I'd like to bring these conversations together so we can come to a consensus.

I think we're all in agreement that having an explicit (uncurried) `page` argument on every helper call is not preferred.

What do you think of extending the puppeteer `page` object with **em** helper functions? You both suggested something like this, although @trevinhofmann I think you went in a different direction with `createPuppeteerHelper` and `createPuppeteerTest`.

I like how `createPuppeteerTest` preserves a per-test setup and `page` object, which allows for running tests concurrently. I'm not sure if it particularly reduces complexity compared to the current implementation. It shifts the complexity out of the helper index but forces to wrap every test and every helper in the slightly opaque create functions.

If we're going to commit to the per-test setup and `page` object, I think we should push as much of the complexity into `setup` as possible. That is where the `page` object is created, so that's probably where the helpers should be initialized. `createPuppeteerTest` wraps `setup`, but I don't think we ever intend to call them separately so they might as well be combined.

**Comment by raineorshine** [comment]
From @finkef (join the party 🎈), regarding concurrency:

> Jest supports that as well, but I've yet to come across a codebase that actually uses this. Feels like this opens up soooo many issues. Elixir has a nice prop-testing library, but they have plenty of abstraction around it to make sure you don't run into concurrency issues.

At the risk of severely backtracking on the above discussion... if we're not using concurrency, a shared `page` object would simplify the design. We could even import the helpers at the top-level of each test file. No currying or test wrappers needed.

**Comment by mstrofbass** [comment]
> From @finkef (join the party 🎈), regarding concurrency:
> 
> > Jest supports that as well, but I've yet to come across a codebase that actually uses this. Feels like this opens up soooo many issues. Elixir has a nice prop-testing library, but they have plenty of abstraction around it to make sure you don't run into concurrency issues.
> 
> At the risk of severely backtracking on the above discussion... if we're not using concurrency, a shared `page` object would simplify the design. We could even import the helpers at the top-level of each test file. No currying or test wrappers needed.

Yeah, for me it's a toss up between the two and don't think there's an optimal solution. My proposal was simply an alternative if we wanted to support concurrency.

**Comment by raineorshine** [comment]
I was hoping we could reach a consensus, but it appears opinions are pretty divided. 

Given the desire to keep tests simple, I think we ought to abandon concurrency support and use a shared page object. I'd like to export a shared page object that all helpers can import without prefixing with `global.` or having it passed in as an argument. Please let me know if this is possible. Thanks! 🙂

**Comment by mstrofbass** [comment]
I think that's a great idea...should be pretty quick to put together.
