### ISSUE TITLE
ColorPicker style regression

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2470]
This is a regression from #2429.

## Steps to Reproduce

Open the ColorPicker by clicking the toggleColorPicker toolbar button.

## Current Behavior

<img width="333" alt="Brave Browser 2024-10-19 21 41 34" src="https://github.com/user-attachments/assets/f6f31684-8a00-4c0c-a6fc-99e82755c013">

## Expected Behavior

<img width="296" alt="Brave Browser 2024-10-19 21 38 34" src="https://github.com/user-attachments/assets/0dbe3b21-432d-43a9-848a-0a3be257f028">

**Comment by ohrytskov** [comment]
This issue seems to be an update request rather than a regression, linked to the scope of a milestone. The color icon, which had no specific description or special requirement initially, was originally rendered as span elements and has now been updated to svg. The new design includes a white border inside, suggesting that this fresher look should be applied universally. It's also worth mentioning that the color picker inside uses the exact same color icon multiple times for all colors, which wasn't immediately obvious. This has been addressed and resolved, as confirmed in this GitHub pull request: https://github.com/cybersemics/em/pull/2462.

**Comment by raineorshine** [comment]
Thanks, it looks much better now! I'll mark this as complete.
