### ISSUE TITLE
Uncaught Exception: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by zukilover** [cybersemics/em#2583]
Here's a log from vitest:

```
Vitest caught 2 unhandled errors during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯ Uncaught Exception ⎯⎯⎯⎯⎯
ReferenceError: document is not defined
❯ Timeout._onTimeout src/redux-middleware/scrollCursorIntoView.ts💯30
❯ listOnTimeout node:internal/timers:581:17
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
❯ processTimers node:internal/timers:519:7
```

**Comment by raineorshine** [comment]
https://github.com/cybersemics/em/actions/runs/11801187295/job/32876029673?pr=2582

**Comment by mstrofbass** [comment]
Taking a first pass at debugging this and this might be causing the problem:

https://github.com/cybersemics/em/blob/67457b39353e4a0f3540b00cbefdb38bd4026dfe/src/redux-middleware/scrollCursorIntoView.ts#L108-L115

My guess is that some state change during the tests is triggering the setTimeout and the delayed function isn't being called prior to the test completing. 

I think that part of the difficulty with this in the tests is that all of the store operations _look_ synchronous (because they don't return promises) but in this case there may be an asynchronous call generated anyways (via setTimeout), so the test writer doesn't know that they should either use fake timers or clear timeouts/intervals. 

I might be able to recreate this by increasing the setTimeout delay a lot but since it (1) is not cropping up every time and thus (2) is unlikely to hide a test failure (i.e., be a false positive), I'll probably have to look into this on Friday.

One cheap way to fix this and also decrease the chances it will crop back up may be to set the duration used by the setTimeout to zero (like we do in the e2e tests).

**Comment by raineorshine** [comment]
Thanks, that's informative. Dealing with asynchronous timing seems to be a real challenge in tests.

> One cheap way to fix this and also decrease the chances it will crop back up may be to set the duration used by the setTimeout to zero (like we do in the e2e tests).

Yes, I think the animation durations should definitely be zero'd out in the RTL tests just like the E2E tests.

--

There are a couple troubleshooting questions that come to mind:

1. Since this is a recent regression, which commit introduced it?
2. Why would `document` ever be undefined? Does JSDOM get deallocated at a certain point in the test lifecycle? Maybe other people have run into this issue and we could find some hints about how to avoid it.

**Comment by raineorshine** [comment]
I did some extensive bisecting today to try to identify the offending commit. Since I'm not able to reproduce on my local machine, each test attempt involved force pushing a commit to a PR to trigger the CI.

Here are my results (from most recent to least recent)

Notably ced54cc9474 (bad) and dd1893d0991 (good) are contiguous, which means that logically ced54cc9474 would have introduced the regression. Bizarrely, ced54cc9474 actually just adds some puppeteer tests. It makes no changes to the application code or the unit tests, so I don't know how it could possibly break the unit tests. That is probably worth re-testing. I wore the tread off dd1893d0991 (30 successful runs) so that is probably reliable.

## Bad commits

a57f90ae806 
21af652c8ee
v300.30.36 Failed after 2 attempts
4b0e357743a369cd3d9b6d6ec0e6878632d51868 Failed after 6 attempts
v300.30.35 Failed after 12 attempts
5ce2fa0daaa Failed after 7 attempts
46c5d5b5f02 Failed after 1 attempt
42a5d76ca4d Failed after 1 attempt
aa98cd95ba0 Failed after 4 attempts
ced54cc9474 Failed after 1 attempt

## Good commits

dd1893d0991 No failures after 30 attempts
6e4fa5311c6 No failures after 20 attempts

**Comment by mstrofbass** [comment]
I can't get this to trigger on purpose. I've tried to increase the timeout durations but the callbacks don't even appear to be called if the tests end before timeout. I was able to verify this by returning a promise that didn't resolve until after the `scrollCursorIntoView`, which ended up allowing the callback to get triggered.

IMO the immediate solution is just to add an if-check for `document`, which should prevent the error from occurring. 

https://github.com/cybersemics/em/pull/2623

**Comment by mstrofbass** [comment]
This appears to only occur in the `jump.ts` test. Pasting the full error here for reference:

```
⎯⎯⎯⎯⎯ Uncaught Exception ⎯⎯⎯⎯⎯
ReferenceError: document is not defined
 ❯ Timeout._onTimeout src/redux-middleware/scrollCursorIntoView.ts:100:30
 ❯ listOnTimeout node:internal/timers:581:17
 ❯ processTimers node:internal/timers:519:7

This error originated in "src/shortcuts/__tests__/jump.ts" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
This error was caught after test environment was torn down. Make sure to cancel any running tasks before test finishes:
- cancel timeouts using clearTimeout and clearInterval
- wait for promises to resolve using the await keyword
```

**Comment by mstrofbass** [comment]
Another option would be to try fakeTimers. It does not appear to cause any problems with the current tests (i.e., it doesn't require moving the timers forward to get the tests to pass). 

I would be tempted to kill PR #2623 in place of adding the following to `jump.ts`:

```javascript
beforeEach(vi.useFakeTimers)
afterEach(vi.useRealTimers)
```

And then see if we could get it to trigger.

**Comment by mstrofbass** [comment]
~16 runs of the tests via GitHub actions with the use of fake timers and no errors. Leaning towards https://github.com/cybersemics/em/pull/2624

**Comment by raineorshine** [comment]
Yes, I would prefer fake timers whenever possible.

Thanks for doing the additional testing!
