### ISSUE TITLE
Warning: An update to ThoughtContainer inside a test was not wrapped in act(...)

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#2584]
Many warnings like this are printed to the test output:

```
Warning: An update to ThoughtContainer inside a test was not wrapped in act(...).

When testing, code that causes React state updates should be wrapped into act(...):

act(() => {
  /* fire events that update state */
});
/* assert on the output */

This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
    at ThoughtContainer (/home/runner/work/em/em/src/components/Thought.tsx:103:3)
    at div
    at Subthought (/home/runner/work/em/em/src/components/Subthought.tsx:34:3)
    at div
    at VirtualThought (/home/runner/work/em/em/src/components/VirtualThought.tsx:40:3)
    at div
    at div
    at div
    at LayoutTree (/home/runner/work/em/em/src/components/LayoutTree.tsx:266:30)
    at div
    at div
    at Content (/home/runner/work/em/em/src/components/Content.tsx:48:42)
    at div
    at MultiGestureIfTouch (/home/runner/work/em/em/src/components/AppComponent.tsx:93:32)
    at div
    at AppComponent (/home/runner/work/em/em/src/components/AppComponent.tsx:120:42)
    at div
    at TouchMonitor (/home/runner/work/em/em/src/components/TouchMonitor.tsx:14:25)
    at ErrorBoundary (/home/runner/work/em/em/node_modules/react-error-boundary/dist/react-error-boundary.development.esm.js:14:5)
    at ErrorBoundaryContainer (/home/runner/work/em/em/src/components/ErrorBoundaryContainer.tsx:135:35)
    at Provider (file:///home/runner/work/em/em/node_modules/react-redux/dist/react-redux.mjs:1036:3)
    at DndProvider (file:///home/runner/work/em/em/node_modules/react-dnd/dist/core/DndProvider.js:35:11)
    at DragAndDropContext (/home/runner/work/em/em/src/components/DragAndDropContext.tsx:29:31)
    at App
    at DndProvider (file:///home/runner/work/em/em/node_modules/react-dnd/dist/core/DndProvider.js:35:11)
```

https://github.com/cybersemics/em/actions/runs/11801187295/job/32876029673?pr=2582

**Comment by mstrofbass** [comment]
The gist of these is that they are usually caused by asynchronous actions that don't complete until after the test has completed. These appear to fall into a couple of categories, with some of them possibly being intermittent.

The first category is `Status` updates. These are caused by the `offlineStatusStore.ts` timeouts triggering state updates after the end of the tests. I have a concern that these are always a problem with tests that require `createTestApp` and that if we haven't had to fix them in the test itself it's basically because the test ends up taking long enough that the status updates happen to complete in time. 

We can't fix this in the clean up function because the error occurs _if the test has ended_, and so it has to be handled prior to test completion. I think the robust solution to this is to somehow eliminate the status updates from running when we're in the tests. We could do this by setting the timeouts to 0 like we do with the e2e tests or could simply mock the `offlineStatusStore`. I like the latter because we're not bringing logic to support tests into the components themselves and exerting more control over the testing environment. I'm not sure how easy it would be to do this though so the former may be the better solution for now.

The second category are state updates that result in asynchronous updates. These are a bit more difficult because they can be intermittent (sometimes they complete before the end of the test and sometimes they don't) but also because there is no immediately clear pattern (to me) when they'll occur and they are sometimes related to wholly unrelated functionality, like transitions.

The transitions are a good example because they result in a large stream of logs (I assume for each render) and they may be completed unrelated to the functionality being tested. Further, it may not be immediately obvious when an action will trigger a transition, so it may be difficult to know when something needs to be wrapped or writing the tests to use `waitFor` or equivalent.

**Comment by mstrofbass** [comment]
I am submitting a PR that removes all of the warnings that I can currently find. As I noted above, some of these may be intermittent so if you happen to see any new ones pop up, please let me know.

**Comment by raineorshine** [comment]
> The first category is `Status` updates. These are caused by the `offlineStatusStore.ts` timeouts triggering state updates after the end of the tests. I have a concern that these are always a problem with tests that require `createTestApp` and that if we haven't had to fix them in the test itself it's basically because the test ends up taking long enough that the status updates happen to complete in time.
> 
> We can't fix this in the clean up function because the error occurs _if the test has ended_, and so it has to be handled prior to test completion. I think the robust solution to this is to somehow eliminate the status updates from running when we're in the tests. We could do this by setting the timeouts to 0 like we do with the e2e tests or could simply mock the `offlineStatusStore`. I like the latter because we're not bringing logic to support tests into the components themselves and exerting more control over the testing environment. I'm not sure how easy it would be to do this though so the former may be the better solution for now.

Thanks! I'm okay with either approach. `offlineStatusStore` is mostly disabled at the moment, but it will be re-enabled when we get a new sync engine (to replace YJS) and will likely use the same timeout method to wait for the server connection.

> The second category are state updates that result in asynchronous updates. These are a bit more difficult because they can be intermittent (sometimes they complete before the end of the test and sometimes they don't) but also because there is no immediately clear pattern (to me) when they'll occur and they are sometimes related to wholly unrelated functionality, like transitions.
> 
> The transitions are a good example because they result in a large stream of logs (I assume for each render) and they may be completed unrelated to the functionality being tested. Further, it may not be immediately obvious when an action will trigger a transition, so it may be difficult to know when something needs to be wrapped or writing the tests to use `waitFor` or equivalent.

Got it. Yeah, these can be tricky. However, these warnings are all fairly recent. If we can track them to a specific commit, that may give us a hint about where they are coming from.
