### ISSUE TITLE
Recently Edited Click Zone

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#451]
There is a dead click zone on the edge of the screen, I believe due to `.content` padding. 

When clicking or tapping in this zone, open the Recently Edited Sidebar. 

Disable when `state.showModal` is set.

**Comment by pushkov-fedor** [comment]
By dead zone do you mean left, bottom and right padding?
![Screenshot from 2020-05-12 13-40-03](https://user-images.githubusercontent.com/32064251/81649716-f49b3000-945a-11ea-8ff2-e7e410e4007e.png)
It looks like we just need to dispatch `toggleSidebar` inside onClick event. It looks like 0.5-1 hour for testing and development. It could be difficulties with left side, because there are drag-source and drag-target areas of thoughts and we should deal with `onClick/mouseDown` events and it could take extra time. Correct me please, if i am wrong somewhere.

**Comment by raineorshine** [comment]
> By dead zone do you mean left, bottom and right padding?

Just the space from the left edge of the screen to the leftmost bullet!

> It looks like we just need to dispatch toggleSidebar inside onClick event. It looks like 0.5-1 hour for testing and development.

Okay, sounds good!

>  It could be difficulties with left side, because there are drag-source and drag-target areas of thoughts and we should deal with onClick/mouseDown events and it could take extra time.

Good observation, although hopefully it won't be an issue. onClick has much less interference with the drag events.
