### ISSUE TITLE
Thought duplicated on ArrowDown in context view

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#551]
## Steps to Reproduce

- a
  - m
    - x
- b
  - m

1. Create the above thought structure
2. Select `a.m` and activate Context View.
3. Select `a.m~.a`
4. Hit `ArrowDown`

## Current Behavior
`a.m` gets duplicated and there is a duplicate key error.

## Expected Behavior
No thoughts should be modified on `ArrowDown`. The cursor should move from `a.m~.a` to `a.m~.b`

**Comment by anmolarora1** [comment]
Hi @raineorshine - Here are my findings with this issue -
The first thing which seems wrong is the `onChangeHandler` being called on `setSelection`. I couldn't find a way to bail out of that due to the way ReactContentEditable handles setSelection.
After some more digging, the real problem turned out to be with the values with which the `onChangeHandler ` was being called -  `oldValue - x` & `newValue - a`. 

![nocontext](https://user-images.githubusercontent.com/7765764/79497872-b875da80-8028-11ea-9a67-03561da78b2b.png)
![context](https://user-images.githubusercontent.com/7765764/79497874-ba3f9e00-8028-11ea-9c92-821bc6ed97f4.png)

So instead of unmounting the existing thought's children and replacing the sub-tree with its contexts, the component assumes that the thought's value was changed from `x` to `a` and hence, the onChange being called with false values.

So,
**The root issue** - Children of thought (which is turned into a context-view) were not unmounting.

**Cause** - In `subThoughts.js`, we're using `child.rank` as the key for `Thought`. And the keys of thought `x` and context `a` were the same - `0`.
(And there can be many such keys which are duplicated)

**Solution** - For the new context tree to be mounted, thoughts and contexts need to have different keys. So `child.rank` alone can't be used as the key.
For now, I'm using this -
`key={${child.rank}${child.context ? child.context.join('') : ''}}`
It works though, but I'm sure we can have a simpler value that is unique, which shouldn't be a big deal.

Please share your opinion.

**Comment by raineorshine** [comment]
That sounds reasonable to me, but I'd like @shresthabijay to make the final call. We have changed the `key` a couple times due to subtle bugs. What are your thoughts on this issue?

**Comment by shresthabijay** [comment]
@anmolarora1 @raineorshine  Good catch! In previous implementation I used only rank as key because it was unique for all nodes in a context . It only changed for a `thought` when it was re-ordered within it's context. But I forgot to take context view into consideration. Adding view to the key works properly. When view is toggled all the old nodes will unmount and all the new nodes will mount instead of taking over instance of any old node with same key. 
I have tested the solution. I also checked if it introduced any previous regressions that was related to keys. It looks good to me!

**Comment by raineorshine** [comment]
@shresthabijay Thanks, that's great. One question. When switching from normal view to table view or prose view, thoughts are animated into their new positions. Does the unmounting interrupt this, or does it still animate properly between views?

**Comment by shresthabijay** [comment]
@raineorshine We animate `ul` wrapper using `distance-from-cursor` logic instead of animating individual thoughts. So animations works properly.

**Comment by raineorshine** [comment]
The table view and prose view don't use `distance-from-cursor` logic, so I'm not sure how that applies, but maybe you are right.

If it seems like a reasonable approach @anmolarora1, your are welcome to proceed.
