### ISSUE TITLE
Clicking to the left or right of the content should call cursorUp

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#564]
This seems to be a regression. Why isn't `clickOnEmptySpace` being called?

https://github.com/cybersemics/em/blob/dev/src/components/Content.js#L65-L76

There are at least two layers of click handlers: `Content` and `Editable`. The solution should be careful to preserve the other click behaviors.

**Comment by shresthabijay** [comment]
@raineorshine This is because there is another wrapper `div` that is stopping event propagation.

https://github.com/cybersemics/em/blob/f9cd5982ea4067571b90ad9b96915b3588c503ea/src/components/Content.js#L84-L91

In JS due to event bubbling, event handling starts from the nested nodes to the outer nodes. Since the inner div is simply stopping further propagation, so the main content div is not receiving any click events at all. We need to remove the `stopEventPropagation` function in the inner div.

https://github.com/cybersemics/em/blob/f9cd5982ea4067571b90ad9b96915b3588c503ea/src/components/Content.js#L54-L57

I tested by removing this function and it works properly. I don't really think we need this anymore unless there is still some event this function is preventing. If you know about it please let me know! If not for it I will send a PR fix right away.

**Comment by raineorshine** [comment]
Hmmm I think you're right! I used `git blame` to try to trace down the original motivation. I'm not 100% sure, but my best guess is it had something to do with this:

https://github.com/cybersemics/em/blob/50d80f4d27fb2fc5608b8a2812d9a70da6313918/src/components/AppComponent.js#L106-L107

Regardless, I tested on desktop and mobile, including the specific case described in the comment, and it appears to not be a problem any more!

The PR's are those with only deletes 😄
