### ISSUE TITLE
TutorialStepAutoExpand: undefined in instructions

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#565]
`Try clicking on "Hello" to hide the subthought "undefined"`

**Comment by shresthabijay** [comment]
@raineorshine  To understand this issue let's recreate it by steps:

For example we have this strcuture:

- HELLO
- NAMASTE (cursor)
  - HOLA

The current implementation uses `rootSubthoughtNotCursor` to find the thought that need to be clicked to hide the subthought ( descendant of the current cursor).
 
i.e Try clicking "HELLO" to hide subthought "HOLA" **(This makes sense)**

So when user clicks "HELLO" `rootSubthoughtNotCursor` now will give "NAMASTE" and the subthought to hide will be "undefined" because it doesn't have any subthought at all. Also I suppose it should trigger next button to appear but it doesn't. I couldn't understand the logic behind it.

i.e Try clicking "NAMASTE" to hide subthought "undefined".

Also in cases like this:

- HELLO (cursor)
- EMPTY THOUGHT

i.e Try clicking "" to hide subthought "undefined" **(This makes no sense)**

Worse when user deletes all the thoughts in the tree. Trying to add will result in application crash.

TypeError: Cannot read property 'length' of null (head.js)

For first two cases we can easily check for these conditions and show user specific instructions. 

Also there is a problem with next button not appearing after user follows the instruction. I will need your help to get bit of insight on the current implementation. 

Also there is the last problem where user deletes all the thoughts and on adding thought application crashes. It occurs because the user can delete thoughts, change focus etc during tutorial. They are supposed to follow specific instructions but in case when they don't , the application shouldn't crash or show weird behaviors either.

**Comment by raineorshine** [comment]
> @raineorshine To understand this issue let's recreate them.

Thanks for the detailed analysis!

> **i.e Try clicking "HELLO" to hide subthought "HOLA" (This makes sense)**
> 
> So when user clicks "HELLO" `rootSubthoughtNotCursor` now will give "NAMASTE" and the subthought to hide will be "undefined" because it doesn't have any subthought at all. 

Can you clarify, which thought doesn't have any subthought at all? When `rootSubthoughtNotCursor` is `NAMASTE`, it will have the subthought `HOLA`, regardless of whether it's expanded or not.

> Also I suppose it should trigger next button to appear but it doesn't. I couldn't understand the logic behind it.

For better or worse, the next button has its own logic to determine if it is visible: https://github.com/cybersemics/em/blob/dev/src/components/Tutorial/TutorialNavigationNext.js#L41-L68

Also, some steps auto-advance without requiring the user to hit the Next button. That auto-advance usually happens in a reducer: https://github.com/cybersemics/em/blob/dev/src/reducers/setCursor.js#L99-L112

> 
> **i.e Try clicking "NAMASTE" to hide subthought "undefined".**
> 
> Also in cases like this:
> 
> * HELLO (cursor)
> * EMPTY THOUGHT
> 
> **i.e Try clicking "" to hide subthought "undefined" (This makes no sense)**

Yes, neither of these make sense. I believe these are invalid states that are showing up due to the broken auto-advance. If you fix the first issue (auto-advancing in `setCursor` when `HELLO` is focused), then this won't happen at all.

> 
> **Worse when user deletes all the thoughts in the tree. Trying to add will result in application crash**.
> 
> _TypeError: Cannot read property 'length' of null (head.js)_

Yes, this should be handled by asking the user to either go back or recreate the necessary structure for the tutorial step.

> ### Issues in summary
> * [ ]   For first two cases we can easily check for these conditions and show user specific instructions. I need you help to decide what we should do.

I think fixing the auto-advance in the first case may solve both.

> * [ ]   Also there is a problem with next button not appearing after user follows the instruction. I will need your help to get bit of insight on the current implementation.

I think it's likely an auto-advance instead of the next button. (This is arguably not a great user experience but that's a separate issue).

> * [ ]  Also there is the last problem where user deletes all the thoughts and on adding thought application crashes. It occurs because the user can delete thoughts, change focus etc during tutorial. They are supposed to follow specific instructions but in case when they don't , the application shouldn't crash or show weird behaviors either.

The user should be able to use all of the commands as normal, but the tutorial should adapt and let them know what needs to be done to resume.

**Comment by shresthabijay** [comment]
> Can you clarify, which thought doesn't have any subthought at all? When `rootSubthoughtNotCursor` is `NAMASTE`, it will have the subthought `HOLA`, regardless of whether it's expanded or not.

If cursor is in `NAMASTE` , `rootSubthoughtNotCursor` returns `HELLO` and `HELLO` doesn't have any children. That is why it returns `undefined`.

**Comment by shresthabijay** [comment]
> Yes, neither of these make sense. I believe these are invalid states that are showing up due to the broken auto-advance. If you fix the first issue (auto-advancing in `setCursor` when `HELLO` is focused), then this won't happen at all.

I didn't know there was auto advanced. I think fixing it will solve these issues.

**Comment by shresthabijay** [comment]
@raineorshine I will start working on fixing auto advance right away.

**Comment by shresthabijay** [comment]
@raineorshine I looked into auto advance logic and my initial thought was that this particular seems to causing the problem.

https://github.com/cybersemics/em/blob/75d480313b39e7abf428e47bf945e6155d22268f/src/reducers/setCursor.js#L103 

 For example:

- A
  - B (cursor)
- C

- A
- C (cursor)

`expandThoughts` also returns cursor thought with no children as expanded. When cursor is at `B` , `__ROOT__` , `A` and  `B` (cursor) is returned as expanded. When cursor is at `C` , both `__ROOT__` and `C` (cusrsor) is returned as expanded. The condition (L103) referenced above is expecting that during expand tutorial when `C` is clicked , the expanded thoughts will just be `__ROOT_` (i.e  no of expanded thoughts is 1). But actually the `expanded.length` is 2 because `C` is also returned as expanded. 

We can update the logic to become `expanded.length === 2`. It works but auto advance for this tutorial is dependent on user being at level 1 depth cursor being at direct children of one of these level 1 thoughts. If user has created multiple nested thoughts during tutorial and is not at level 1 depth then  `expanded.length === 2` won't always work. Either we should prompt user to create exact structure like given example above or we should write auto advance logic adapting the user current state in tutorial. 

**If we follow instruction properly with updated logic the auto advance works properly for the tutorial. But strangely it doesn't hide the thought when we click away.**

![chrome-capture (11)](https://user-images.githubusercontent.com/25879100/80198094-5415d500-863f-11ea-82e6-3e187361f4ce.gif)

I used Redux Dev Tools and noticed that `setCursor` action dispatched during auto advance 
 was preventing new cursor to be updated to the store. The problem was this function called `settings` which is called when `tutorialNext` is true. 

https://github.com/cybersemics/em/blob/75d480313b39e7abf428e47bf945e6155d22268f/src/reducers/setCursor.js#L136-L147

`settings` calls and returns `existingThoughtChange` . Since cursor hasn't been updated yet `existingThoughtChange` returns old cursor, so new cursor update is missed. I have no idea why setting calls `exisitingThoughtChange`. Please let me know about your thoughts on this.

**Comment by raineorshine** [comment]
Great assessment, thank you.

> Either we should prompt user to create exact structure like given example above or we should write auto advance logic adapting the user current state in tutorial.

Let's do the latter. I want the user to be free to create any content they want, and have the tutorial adapt to them.

> I have no idea why setting calls `exisitingThoughtChange`.

What a mess :/.

`settings` calls `existingThoughtChange` because Settings are just thoughts. They are updated just like any other thought. So the `settings` reducers is just a wrapper for `existingThoughtChange`.

> Since cursor hasn't been updated yet `existingThoughtChange` returns old cursor, so new cursor update is missed. 

Great catch. I would say the issue has to do with passing a stale `state` to `settings`, here:

https://github.com/cybersemics/em/blob/75d480313b39e7abf428e47bf945e6155d22268f/src/reducers/setCursor.js#L137

If instead we pass the state with an updated cursor, maybe that will fix it.

Not sure if there is a better way to compose reducers... I'm open to feedback!

**Comment by shresthabijay** [comment]
> Great catch. I would say the issue has to do with passing a stale `state` to `settings`, here:

We can just pass updated cursor at the end , so that it will just replace old cursor in the object.

**Comment by shresthabijay** [comment]
> Let's do the latter. I want the user to be free to create any content they want, and have the tutorial adapt to them.

I will start working on it. I will get back to you soon.

**Comment by shresthabijay** [comment]
> Not sure if there is a better way to compose reducers... I'm open to feedback!

I am looking into it. We need a better way to chain reducers.

**Comment by raineorshine** [comment]
> > Not sure if there is a better way to compose reducers... I'm open to feedback!
> 
> I am looking into it. We need a better way to chain reducers.

Removing side effects is probably a good first step 😂

**Comment by shresthabijay** [comment]
> Removing side effects is probably a good first step 😂

Sure  😂
