### ISSUE TITLE
existingThoughtMove: Old context not deleted

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#614]
Sometimes when a thought is moved, its descendants are not properly moved from the old context. 

Here `Week` and all its descendants were moved to `/Today/Week`. `A` incorrectly still exists in the `/Week` context. 

![6C55B891-DB4E-47A4-B34C-BBD9DBB71029](https://user-images.githubusercontent.com/750276/80723244-a2065f00-8abd-11ea-90ce-309005be7756.jpeg)

## Possible causative factors;

- [x] ~Root?~ No
- [x] ~Different thoughts with same hash?~ No
- [x] ~Race condition?~ No
- [x] ~Moving to/from ancestor vs sibling?~
- [x] ~Drag only or indent?~ Both
- [x] ~Rank?~ Yes!

## Steps to Reproduce
- a
  - b
    - c

1. Move `b` before `a`:

- b
  - c
- a

2. Move `b` after `a`:

- a
- b
  - c

3. Indent or move `b` within `a`:

- a
  - b
    - c

## Expected Behavior

The thoughts should return to their original state:

- a
  - b
    - c

## Current Behavior

`c` exists in two contexts, the old context and the new context of the last move:

- a
  - b
    - c~
      - a • b
      - a

**Comment by shresthabijay** [comment]
@raineorshine Another inconsistency related to this issue. Please follow all the steps as above and then delete thought '**a**'. Then type add an empty thought and type '**c**'.

### Expected Behavior
Newly added thought '**c**' shouldn't have multiple context. 

### Current Behavior
Thought '**c**' is still is available as subthought of deleted thought '**b**'.  

![chrome-capture (2)](https://user-images.githubusercontent.com/25879100/80854399-a49cbc00-8c57-11ea-85e4-77e41274bdcd.jpg)

**Comment by shresthabijay** [comment]
@raineorshine It really took some time to pin point the root cause of this issue. I first started off by reproducing it and looking at the changes of `contextIndex` and `thoughtIndex` . I also tried different variations of steps to reproduce it. I noticed that when we move **a** before **b**, instead of **b** after **a** at the second step you mentioned above, then the issue doesn't occur. So I looked at changes happening to `contextIndex` and `thoughtIndex` specially at second step of the process following both variation (one that caused issue and other that didn't). Finally I noticed that after executing second step, rank of thought '**c**' given by `contextIndex` was not matching the rank given by `thoughtIndex`.

After going through all the logic of `exisitingThoughtMove` , I found why exactly **c** still was available in two context. `recursiveUpdates` iterates through all the children of the `oldThought` and removes old context and adds new updated context. Here `removeContext` doesn't remove `oldContext` at step three. Since at second step rank thought **c** rank is already out of sync between `thoughtIndex` and `contextIndex`, so this function doesn't filter out the old context.

https://github.com/cybersemics/em/blob/0b3f1628d334da3ffd35be0f1379cb8a315d018a/src/reducers/existingThoughtMove.js#L89

But the question is why is the rank out of sync ? To understand that we need how `addContext` is used . This function has a third parameter called `rank` which will be updated along side provided context.

https://github.com/cybersemics/em/blob/0b3f1628d334da3ffd35be0f1379cb8a315d018a/src/util/addContext.js#L8-L16 

 Inside `recursiveUpdate`, `nextLastRank`  of `oldThought` is being calculated. And iterating all it's children, `movedRank` is calculated by increasing `nextLastRank`  by 1. It is being passed to `addContext` function as third parameter. 

https://github.com/cybersemics/em/blob/0b3f1628d334da3ffd35be0f1379cb8a315d018a/src/reducers/existingThoughtMove.js#L88

**So whenever a thought is moved, all of it's descendants rank is increased by 1 recursively. But is is only updated for `thoughtIndex` but not in `contextIndex` introducing inconsistency. After that if the same thought is moved to another context, it won't remove older context from thought causing this issue.**

I really don't understand why rank of all the descendants of moved thought is being updated ? With my understanding, only the moved thought's (i.e '**b**') rank needs to be updated. It's descendants thoughts can keep their rank as it is. Just passing the `child.rank` instead of `movedRank` is working. Please let me know if my understanding is incorrect.

**Comment by raineorshine** [comment]
Ah, yes! What a tricky issue!

First of all, thank you so much for the thorough investigation and explanation.

This appears to be a regression from https://github.com/cybersemics/em/commit/1390ffa86591a69c1ff5b56fac948f22bd97b40e.

Please read the original issue. This will explain a lot about the updated ranks. They have to be updated when merging siblings.
https://github.com/cybersemics/em/issues/25

That is definitely a problem that they are updated in `thoughtIndex` but not `contextIndex`!

Given the reasoning for updating the ranks, let me know if you can come up with a solution or have any more questions.
