### ISSUE TITLE
deleteThought: Delete thought from context.

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#737]
Test: ed27494a
Branch: `737`

**Comment by pushkov-fedor** [comment]
What does this issue means? :)

**Comment by raineorshine** [comment]
Sure! It deserves some explanation the first time! 

This issue uses test-driven development. A failing test already been written in ed27494. The test itself describes the problem better than any description in natural language. Read the test to see the steps to reproduce. Then branch directly from branch `737`. To complete the task, make the test pass.

**Comment by pushkov-fedor** [comment]
Okay. Am i right, that deleting thought from ContextView doesn't work at all now, because i fell on `TypeError: Cannot read property 'value' of undefined` inside `pathToContext`? I can take this issue. I haven't yet worked with ContextView, but thanks to you, we have good description about this in Technical Review. What about 3-4 hours for this?

**Comment by raineorshine** [comment]
> Okay. Am i right, that deleting thought from ContextView doesn't work at all now, because i fell on `TypeError: Cannot read property 'value' of undefined` inside `pathToContext`? 

Yes

> I can take this issue. I haven't yet worked with ContextView, but thanks to you, we have good description about this in Technical Review. What about 3-4 hours for this?

Sure! Context view is quite tricky, so take your time but careful not to get lost :).
