### ISSUE TITLE
Split thought breaks on formatting tags

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#742]

**Comment by shresthabijay** [comment]
@raineorshine The issue is that the thought is splitting from wrong offset with values with formatting tags. `ContentEditable` renders html. So there can be multiple nodes inside `ContentEditable`.

If thought has value with formatting tags. Let cursor after `am`
```html
<i>I am italic <b>I am| bold too</b> <i/>
````
With this if we get `focusOffset` , then `<b>` will be taken as base node. That means `focusOffset` will be **5**. But that is incorrect. We need `cursorOffset` to be calculated taking whole `ContentEditable` as base node.

I found a solution for this with help of range selection. So for the given example we can get correct offset. The solution will provide **17** as `cursorOffset` instead of **5**.

I did some research and this was the solution I found.
https://stackoverflow.com/questions/4811822/get-a-ranges-start-and-end-offsets-relative-to-its-parent-container/4812022#4812022

But there is another problem we have to solve. The solution will calculate offset after converting html to string. But the value we split still has formatting tags in it. 

`I am italic I am| bold too`

**17** is correct offset here.

But actual value we are going to split is as follows. 
```html
<i>I am italic <|b>I am bold too</b> <i/>
````
Taking **17** will split the value from `<|b>` tag here. 

So we need to find a way around this. I don't think there is any out of the box solution to this without traversing content editable nodes and adding length of all the nodes before focused node. Please let me know what you think about this.

**Comment by shresthabijay** [comment]
Also I would like to mention that we would probably want to split values in a way that it creates perfectly balanced html fragments.

For example:

```html
<i>I am italic <b>I am | bold too</b> <i/>
````

Splitting this should result in two balance html fragments.

```html
<i>I am italic <b>I am </b> <i/>
````

```html
<i><b> bold too</b> <i/>
````

Idk if this is within the scope of this issue. Please let me know.

**Comment by raineorshine** [comment]
I may have a solution for Part II.

After splitting, run each thought's HTML through a cleanup algorithm.
https://github.com/biilmann/javascript-xhtml-purifier

Input:

```html
<p>
  <i>I am italic <b>I am
</p>
<p>
  bold too</b><i/>
</p>
```

Output:

```html
<p>
    <em>I am italic <strong>I am </strong></em>
</p>
<p>
     bold too
</p>
```

It will close the tasks in the first thought and remove them from the second, which seems good enough to me.

**Comment by raineorshine** [comment]
Appears to be a regression:

## Steps to Reproduce

```
<b>hello there</b>
``` 

Set the caret in between "hello" and "there" and hit enter 

## Current Behavior

``` 
- <b>hello there</b>
- 
``` 

## Expected Behavior

```
- <b>hello</b>
- <b>there</b>
```

**Comment by ankitkarna99** [comment]
@raineorshine, I looked into this issue and found the cause of not splitting tags with formatting.

In `action-creators > newThought.ts`, there is a condition for split stored in a variable named `split`. There are multiple factors affecting the split condition but the one causing issue is `selection.isThought()`. 

There are two ways we can solve this issue.

1. **DOM Approach:** The method `selection.isThought` checks if the focusNode itself or the parent of the focusNode is our ContentEditable. But the problem is that when inside of `<b>` or `<i>` tags, the `focusNode.parentNode` is not a content-editable node. So, we refactor the code inside of `selection.isThought` to check the grandparent node in case of the focusNode being inside of `<b>` or `<i>` tags.
2. **Non-DOM Approach:** Get rid of the `selection.isThought` criteria from the split condition, because it seems to work fine without it. I do not know if this could cause a regression.

**Comment by raineorshine** [comment]
Thanks for the analysis!

While I typically would assume that `selection.isThought()` is there for a reason, my guess is that the `splitResult` checks won't pass unless the selection is on a valid thought. Let's remove it and see what happens. If it works, great. If it breaks something, then it's an opportunity to write a unit test for the uncovered case. 

Note that `splitResult` is still heavily dependent on the DOM, so until that is rearchitected this will still overall be a DOM-based split logic.
