### ISSUE TITLE
Note disappears when editing thought

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#766]
## Steps to Reproduce

- A [cursor]
  - `=note`
    - B

Create the above structure and then edit `A`. 

## Current Behavior

Note `B` disappears after edit throttle delay. 

## Expected Behavior

Note should not disappear. 

## Notes
This is likely caused by using `cursorBeforeEdit` instead of `cursor`, or vice versa, in the logic for either determine if the note should be rendered or the logic for fetching the note itself. 

Make sure the solution does not cause a re-render and does not cause a `cursor` regression elsewhere.

**Comment by shresthabijay** [comment]
@raineorshine This issue is quite tricky. It took me some time to understand what was going on. Lets start with how `Subthought` , `Thought` and `Note` are rendered. 

```js
<Subthought>
  <ThoughtContainer>
     <Editable/>
     <Note/>
     <Subthought/> // recursion starts
  </ThoughtContainer>
  <ThoughtContainer>
      <Editable/>
      <Note/>
      <Subthought/> // recursion starts
    </ThoughtContainer>
</Subthought>
```
When a thought is edited all the `Subthoughts` below it re-render but it's parents do not re-render at all. We know `Subthought` renders all the `Thought` component and provides `thoughtsRanked` as props. So when a thought is edited the `Thought` component associated with it re-renders but doesn't receive it's updated `thoughtsRanked` from the parent. Because parent `Subthought` doesn't re-render. So `Note` component still receives old `thoughtsRanked` and doesn't find any note associated with the thought causing it to disappear. 

Maybe we can use `thoughtsRankedLive`. I am working on it. Please let me know if you have queries about the description.

**Comment by raineorshine** [comment]
Thanks, that makes sense. It is indeed a confusing part of the codebase. 

We should be able to get it to work with `thoughtsRankedLive`. It’s important that thoughts do not get re-rendered in the middle of editing.
