### ISSUE TITLE
existingThoughtMove: Hash matched descendants disappear

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#862]
## Steps to Reproduce

- a [cursor]
  - =note
    - note

Activate `subcategorizeOne` or `subcategorizeAll`.

## Current Behavior

- [empty]
  - a
    - Note

## Expected Behavior

- [empty]
  - a [cursor]
    - =note
      - note

**Comment by shresthabijay** [comment]
@raineorshine  This was quite challenging to find. This issue is related to the fact that multiple values can have same hash and with the way `value` of a thought is stored across `thoughtIndex` and `contextIndex`. This issue is not specific to meta `=note` or `subcategorize` shortcut. This issue can be reproduced by moving thought that has at least two descendants with value that generate same `hash` but are slightly different. example: `star-war` and `starwars`.

- big-bang

**Comment by raineorshine** [comment]
Wow, after all this time there was a bug in `existingThoughtMove` we didn't know about! Thanks for identifying the cause and providing the detailed explanation.

It's clear that the value comparisons are causing problems related to exact comparisons vs hashed comparisons. I would love to see you proceed based on your initial analysis. In addition to moving thoughts correctly, make sure that the logic for merging duplicate thoughts is preserved.

Note: The current architecture makes it highly inefficient to move a thought with many descendants. This will need to change, but I see that as a much bigger problem, so I doubt we want to address it here. However it would likely supersede this problem.

> Also we need to change `hasContext` to apply necessary transformation to each value of context for consistent hash. May be this can be done when we start working on unordered context feature that is on hold.

Yes, we should deploy all the changes to the hash function at once, since it will require a manual migration of the data. `ParentEntry` does not store the original `Context` unfortunately, so we will have to generate the hashes from a tree traversal. We should add a `context` property so this is not a problem in the future. At the very least, it will make debugging a lot easier.

**Comment by shresthabijay** [comment]
> It's clear that the value comparisons are causing problems related to exact comparisons vs hashed comparisons. I would love to see you proceed based on your initial analysis. In addition to moving thoughts correctly, make sure that the logic for merging duplicate thoughts is preserved.

Sure. I will work on that.

**Comment by shresthabijay** [comment]
> Note: The current architecture makes it highly inefficient to move a thought with many descendants. This will need to change, but I see that as a much bigger problem, so I doubt we want to address it here. However it would likely supersede this problem.

I agree. This is quite a problem with large number of thoughts. We should continue this in a separate issue.

**Comment by raineorshine** [comment]
FYI I can get the same bug with an exact matching thought not just a hash-matching thought:

## Steps to Reproduce

```
- b
- c
  - d
  - e
    - d
```

Drag (or indent) `c` into `b`.

## Current Behavior

- b
  - c
    - e
      - d (with superscript "2")

## Expected Behavior

- b
  - c
    - d
    - e
      - d

**Comment by raineorshine** [comment]
I fixed the bug with duplicate descendants in #1013. Now we can focus on the bug with hash matched thoughts. Here's a test that can be added to [existingThoughtMove](/src/reducers/__tests__/existingThoughtMove.ts):

```js
it('move with hash matched descendant', () => {

  const text = `
  - a
  - b
    - =note
      - note`

  const steps = [
    importText({ path: RANKED_ROOT, text }),
    existingThoughtMove({
      oldPath: [{ value: 'b', rank: 1 }],
      newPath: [{ value: 'a', rank: 0 }, { value: 'b', rank: 0 }],
    }),
  ]

  // run steps through reducer flow and export as plaintext for readable test
  const stateNew = reducerFlow(steps)(initialState())
  const exported = exportContext(stateNew, [ROOT_TOKEN], 'text/plain')

  // contextIndex
  expect(exported).toBe(`- ${ROOT_TOKEN}
  - a
    - b
      - =note
        - note`)

})
```

**Comment by shresthabijay** [comment]
@raineorshine I have made some changes and opened a PR. I have made the following changes.

- Separate thought value transformation into a separate utility function called `thoughtTransform`.
- Use `thoughtTransform` in `hashContext`.
- Used hashed key comparision for filtering `childrenOld` and `childrenNew` in `contextIndexDescendantUpdates`

It solves disappearing of hash matched thoughts. I have described the issue here.

> But this still doesn't explain missing last thought. The reason for that is `result.value` i.e `starwar` is stored as children of `['sheldon', 'big-bang']` . Also another `result.value` i.e `starwar` is stored as children of `['sheldon', 'big-bang', 'star-wars']`
> 
> * sheldon
>   
>   * big-bang
>     
>     * starwar
> 
> Since hash of context `['sheldon', 'big-bang', 'starwar']` is not equal to hash of `['sheldon', 'big-bang', 'star-wars']`, the last thought is not rendered. This explains the current behavior of missing thoughts, value change and existence of garbage context in the state.

But there are some issues I wanna discuss. Even though hash matched thoughts don't disappear, the original value of the thoughts are not maintained.

- sheldon
- big-bang
  - star-wars
    - starwar
  
After dragging `big-bang` into `sheldon` we get following structure.

- sheldon
  - big-bang
    - starwar
      - starwar

`recursiveUpdates`  overrides the `RecursiveMoveResult` of thoughts with same hash key. We don't have distinction between two thoughts move result with same hash value. 
 
https://github.com/cybersemics/em/blob/f69d008cc4a13dba45b98502bf44628fadf99038/src/reducers/existingThoughtMove.ts#L187-L191

For example:

`big-bang.star-wars` move result will be overidden by `bigbang.star-wars.starwar` move result. Move result contains important attributes related to distinct indivudal thought like `id`, `rank`, `pending` and `path`. This will result in inconsitency and the original value won't be maintained for thoughts. Even though they have same hash key, they are moved into different context, with different ranks. 

Please let me know your thoughts on this.

**Comment by raineorshine** [comment]
> @raineorshine I have made some changes and opened a PR. I have made the following changes.
> 
> * Separate thought value transformation into a separate utility function called `thoughtTransform`.
> * Use `thoughtTransform` in `hashContext`.
> * Used hashed key comparision for filtering `childrenOld` and `childrenNew` in `contextIndexDescendantUpdates`

Great! I love it.

> Even though hash matched thoughts don't disappear, the original value of the thoughts are not maintained.

Yeah, this is a problem.

> `recursiveUpdates` overrides the `RecursiveMoveResult` of thoughts with same hash key.

Yes, this is intended, as `RecursiveMoveResult` corresponds to a `Lexeme` rather than a `Child`. As an aside, this is not the best architecture now but I believe it existed way back before we even had `contextIndex`. Also see next response.

> We don't have distinction between two thoughts move result with same hash value.

As you may know, a `Child` stores the exact value of a thought and a `Lexeme` stores a normalized value (which produces matching hashes for different cases, singular/plural, etc). Following the existing architecture, there is indeed no distinction at the `Lexeme` level, however there should be at the `Path` level (`pathOld/New`, if not the `Context` level (`contextsOld/New`). `Paths` definitely have exact thoughts, but unfortunately the `RecursiveMoveResult` [stores `pathOld`](https://github.com/cybersemics/em/blob/f69d008cc4a13dba45b98502bf44628fadf99038/src/reducers/existingThoughtMove.ts#L181-L182) rather than `pathsOld` (incorrectly I believe). This would cause the loss of the exact value information.

Use of `result.value` and `result.rank` to [create `childrenNew`](https://github.com/cybersemics/em/blob/f69d008cc4a13dba45b98502bf44628fadf99038/src/reducers/existingThoughtMove.ts#L217-L218) is incorrect. It should use the exact values stored in `pathsNew`, once that is corrected.

Please check my logic and let me know if that sounds accurate! Thanks!

**Comment by shresthabijay** [comment]
@raineorshine  I have made some major changes in this PR. Please take a look and let me know if things are working for you. https://github.com/cybersemics/em/pull/1014#issuecomment-771171095
