### ISSUE TITLE
Nested context chain broken

### ISSUE THREAD

**Issue by shresthabijay** [cybersemics/em#875]
I cannot use deeper nested context view without crashing the app. I have tried to narrow it down to these following issues.

1. Inside `chain` the `pivot` index is simply calculated by taking the head `value` of the last chain inside `contextChain` and 
    finding first value inside provided path that matches the `pivot`.
    https://github.com/cybersemics/em/blob/5be62eb42d613aade4fecdecc70974beb16414d8/src/selectors/chain.ts#L14
    But this won't work properly for nested `contextChain`.

     Example:
    - a
      - b
        - c
            - d 
                - c ~
                    - a.b.c
                    - a.b.c.d.c (cursor)

      We can find `thoughtResolved` using `chain` as shown below.

      ```javascript
       const thoughtsResolved = chain(
         updatedState,
         [
           rankThoughtsSequential(['a', 'b', 'c', 'd', 'c']),
         ],
         rankThoughtsSequential(['a', 'b', 'c', 'd', 'c'])
       )

      /*
      [
      { value: 'a', rank: 0 },
      { value: 'b', rank: 1 },
      { value: 'c', rank: 2 },
      { value: 'd', rank: 3 },
      { value: 'c', rank: 4 },
      { value: 'b', rank: 0 },
      { value: 'd', rank: 3 },
      { value: 'c', rank: 4 }
      ]
      */
      ```

     As you can see this is not the expected result. Due to circular nature of `contextChain` a value similar to `pivot` can appear 
     before in a path inside a chain that will cause `pivot` index to be wrong. This will return wrong `thoughtsResolved`.  The 
     actual `thoughtsResolved` should be
     ```
     [
      { value: 'a', rank: 0 },
      { value: 'b', rank: 1 },
      { value: 'c', rank: 2 },
      { value: 'd', rank: 3 },
      { value: 'c', rank: 4 },
      { value: 'd', rank: 1 }
      ]
      ```
2. The `chain` function removes the overlapping head by removing second item from each chain inside `contextChain` where 
     index is greater than zero. But that doesn't work properly.

     Example:
       
   - a
      - b
        - c
            - d 
                - c ~
                    - a.b.c
                        - d ~
                            - a.b.c.d (cursor)
                            - m.d
                    - a.b.c.d.c
                
    - m 
      - d

      Since `contextChain` is calculated by simply concating `thoughtsRanked`, we will have a chain that looks something like this.
      ```javascript
      const thoughtsResolved = chain(
          updatedState,
         [
           rankThoughtsSequential(['a', 'b', 'c', 'd', 'c']),
           rankThoughtsSequential(['a', 'b', 'c', 'd']),
         ],
         rankThoughtsSequential(['a', 'b', 'c', 'd'])
      )

      /*
       [
        { value: 'a', rank: 0 },
        { value: 'b', rank: 1 },
        { value: 'c', rank: 2 },
        { value: 'd', rank: 3 },
        { value: 'c', rank: 4 },
        { value: 'a', rank: 0 },
        { value: 'c', rank: 2 },
        { value: 'd', rank: 3 },
        { value: 'c', rank: 0 }
        ]
       */
       ```
       Since `contextChain` is created simply by concating `thoughtsRanked`. This doesn't work as expected. As you can see the
       overlapping head between first and second context in `contextChain` is `c` but `b` is being removed. This results in wrong 
       `thoughtsResolved`.
        
        Instead it should be something like this.
        ```
        [
         { value: 'a', rank: 0 },
         { value: 'b', rank: 1 },
         { value: 'c', rank: 2 },
         { value: 'd', rank: 3 },
         { value: 'c', rank: 4 },
         { value: 'b', rank: 0 },
         { value: 'd', rank: 2 },
         { value: 'c', rank: 0 }
        ]
        ```

**Comment by raineorshine** [comment]
I agree with your analysis. There may be many simultaneous issues here, but let's start with the [pivot](https://github.com/cybersemics/em/blob/dev/src/selectors/chain.ts#L14-L15). The pivot points to the incorrect item in the path since it is only matched on value. What if we matched it on `id` instead? Or will this still not work for truly circular paths (i.e. `a/b/c~/b/c` where `c` is the same `Child`, as opposed to `a/b/c/d/c` where `a/b/c` is a different `Child` than `a/b/c/d/c` (though they point to the same `Lexeme`).

---

Stepping back a moment, we may want to confirm that the infrastructure actually supports what we're trying to do. i.e. Is it just a matter of fixing bugs in `chain` (and possibly other bugs) or do we need to change the data structure?

There are at least four relevant variables: `state.cursor`, `state.contextView`, `thoughtsRanked`, and `contextChain` (which is built up through the nesting of `Thoughts`).

For your example (1), I believe they would be:

**cursor** - `/a/b/c/d/c/d`
**contextView** - `{ [hashContext[a/b/c/d/c]]: true }`
**thoughtsRanked** - `a/b/c/d/c`
**contextChain** - `[[a,b,c,d,c]]`

I believe that gives us all the information we need to calculate a new `contextChain` and `cursor` as needed. If so, then we can focus on fixing any bugs in `chain` and related functions.

**Comment by shresthabijay** [comment]
> Or will this still not work for truly circular paths (i.e. `a/b/c~/b/c` where `c` is the same `Child`, as opposed to `a/b/c/d/c` where `a/b/c` is a different `Child` than `a/b/c/d/c` (though they point to the same `Lexeme`).

It won't work, id would be same for same `Child` in circular paths.

**Comment by raineorshine** [comment]
Did our recent refactors fix this? If not, what is the next step? Thanks!

**Comment by shresthabijay** [comment]
> Did our recent refactors fix this? If not, what is the next step? Thanks!

Yes. #899 fixed this.
