### ISSUE TITLE
docs script fails

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#889]
The `docs` script is failing due to a recent update, possibly #886.

Please confirm which commit broke the script, and remediate.

https://github.com/cybersemics/em/runs/1277664876

**Comment by anmolarora1** [comment]
@raineorshine The `docs` script was broken due to [this commit](https://github.com/cybersemics/em/pull/886/commits/e4d516b7af792576008d06f15d076adcc83a2d77). To be precise, it was caused due to **typedoc's version update**

However, there's nothing wrong with our code, and the bug is in the plugin [typedoc-plugin-external-module-name](https://github.com/christopherthielen/typedoc-plugin-external-module-name), that we are using.

I've created an issue for the same, so let's wait for the author's response. 
https://github.com/christopherthielen/typedoc-plugin-external-module-name/issues/548

Meanwhile, we can switch back to the older version of `typedoc (0.17.8)` as an interim solution.

**Comment by raineorshine** [comment]
Excellent work! I appreciate the thoroughness and great explanation.

1. Please open a PR to switch `typedoc` back to `0.17.8` as suggested.

2. If you could go ahead and fork `typedoc-plugin-external-module-name` and open a pull request for that change, that'll make it even easier for the developer. It looks like you've narrowed in on exactly what needs to be changed.

Thanks!

**Comment by anmolarora1** [comment]
> 1. Go ahead and fork `typedoc-plugin-external-module-name` and open a pull request for that change, that'll make it even easier for the developer. It looks like you've narrowed in on exactly what needs to be changed. Ideally add a unit test.

> 2. Change our dependency to point to the updated branch on your fork. That will allow us to stay up-to-date on `typedoc` and easily switch to the published plugin when it has been patched.
> 
Sure! I'll do that
