### ISSUE TITLE
Root thought is hidden when `toggleHiddenThoughts` is turned off

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#896]
## Steps to Reproduce

1. Activate `toggleHiddenThoughts`
1. Create `=one`
2. Create `=two`
3. Activate `toggleHiddenThoughts`

## Current Behavior

`=one` and `=two` disappear

## Expected Behavior

The thought under `cursor` (`=two`) should not disappear. All other metaprogramming attributes should disappear.

This is a problem with the root context rendering. It works as expected in non-root contexts:

e.g.

1. Create thought `a`
1. Activate `toggleHiddenThoughts`
1. Create subthought `a/=one`
2. Create `a/=two`
3. Activate `toggleHiddenThoughts`

i.e.:

- a
  - =one
  - =two [cursor]

**Comment by raineorshine** [comment]
@shresthabijay I've assigned this to you since you're familiar with the root rendering in the `Content` component.

**Comment by shresthabijay** [comment]
@raineorshine This is not a problem with root rendering in the `Content` component. This happens to be problem with the logic.

https://github.com/cybersemics/em/blob/f608ca948eb40a4dec0bd01b2aea28250755f647/src/components/Subthoughts.tsx#L415-L425

Let's recreate what happens here when `simplePath` is `RANKED_ROOT`. 

- =one
- =two (cursor)

```javascript
   // Note: path cannot be empty
   const simplePath = RANKED_ROOT

   // Note: cursor is a unrooted path
   const cursor = [{ value: '=two', rank: 1 }] 

  /*
    This logic expects simplePath length to always be 1 less than the childPath. 
    But in case of root Subthoughts, we have RANKED_ROOT instead of an empty path.
  */
   console.log(cursor[simplePath.length]) // undefined
```

Since we are using `RANKED_ROOT` as `simplePath` for root thought, the logic fails. This was causing the unexpected behavior.

I would also like to point out another flaw in this implementation. As you can see in line `424` that `cursor[simplePath.length]` is being compared with `child`. The current logic expects a thought that lies in a `cursor` to have `simplePath` to be proper ancestor of `cursor`. But it is not always true. Specially when `cursor` has one ore more active context view.

- a
  - b
    - c ~
      - a.b
      - i
- i
 - c

Here, let's analyse `a.b.c.b`. `simplePath` and `path` is being represented as `context` for clarity.

`['a', 'b', 'c']` is the `simplePath` and `['a'. 'b', 'c', 'b']` is the cursor. As you can see `simplePath` cannot be a subPath`

Since `cursor` is a `path` so `cursor[simplePath.length]` won't always return the desired `child` from the cursor.

I think we can fix both of the above mentioned problems if we use `appendChild` which is still on active PR #893.

```javascript
/**
 * Returns visible children.
 */
const filterChildren = (state: State, path: Path, simplePath: SimplePath, children: (Child | ThoughtContext)[], showContexts?: boolean) => {
  return children.filter(child => {

    const childSimplePath = getChildPath(state, child, simplePath, showContexts)
    // using resolved child path will always have 
    const childPath = appendChildPath(state, childSimplePath, path)

    const value = showContexts
      ? head((child as ThoughtContext).context)
      : (child as Child).value

    return state.showHiddenThoughts ||
      // exclude meta thoughts when showHiddenThoughts is off
      // NOTE: child.rank is not used by isChildVisible
      isChildVisible(state, pathToContext(simplePath), { value, rank: child.rank }) ||
      // always include thoughts in cursor
      (state.cursor && equalThoughtRanked(state.cursor[childPath.length - 1], head(childPath)))
  })
}
```
`resolvedPath` will always be

**Comment by raineorshine** [comment]
> Since we are using `RANKED_ROOT` as `simplePath` for root thought, the logic fails. This was causing the unexpected behavior.

Got it. Thanks!

> I would also like to point out another flaw in this implementation. As you can see in line `424` that `cursor[simplePath.length]` is being compared with `child`. The current logic expects a thought that lies in a `cursor` to have `simplePath` to be proper ancestor of `cursor`. But it is not always true. Specially when `cursor` has one or more active context view.

Yes, I wonder if that was a regression from the path refactoring. It obviously doesn't make sense to compare a `SimplePath` with a `Path` (the cursor).

Would it be relatively easy to make a test for this case? It would be nice to have coverage here.

> `resolvedPath` will work across context view here. This will also solve the first issue. I have tested this with #893 and it works well.

Yeah, on first glance that seems like it should work.

> I would suggest to separate this logic into separate selector, so that same logic can be consistently used where ever visible children needs to be calculated. One of those places is `Content` component.

Definitely. In fact, I've already consolidated most of this logic in https://github.com/cybersemics/em/blob/dev/src/selectors/getChildren.ts. It is highly modular and uses composition effectively to create a variety of children selectors. Let's make a new selector there and try to compose as much of it as possible from existing function.
