### ISSUE TITLE
Url icon overlaps next thought when wrapped

### ISSUE THREAD

**Issue by raineorshine** [cybersemics/em#986]
## Steps to Reproduce

Adjust length of `aaa...` so that it wraps immediately before the url icon.

```
- a
  - aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    - https://stackoverflow.com/
  - b
```

## Current Behavior

The url icon overlaps the next thought when it is wrapped onto two lines.

![image](https://user-images.githubusercontent.com/750276/104123281-83708d00-5307-11eb-805c-24be8ca4358e.jpeg)

## Expected Behavior

The next thought `b` should be rendered after the url icon. 

The height of `a` should be based on the ThoughtAnnotation, which contains the url icon, rather than the Thought.

**Comment by shresthabijay** [comment]
@raineorshine We need to absolutely position the component `Thought` instead of `ThoughtAnnotation`. Since `ThoughtAnnotation`  has url component, so it will take the necessary space accordingly. This solves the problem however it breaks the bullet cursor overlay. Bullet cursor overlay styling needs to adjusted a lot.

**Comment by raineorshine** [comment]
If we're trying to place the icon back into the document flow, shouldn't we make it position static?

**Comment by raineorshine** [comment]
Making the Thought position absolute is a dramatic change. We do that in flat render but the current layout algorithm relies on the default browser layout with staticly positioned Thoughts. 

I can take a closer look at the CSS here to see if I get an idea of what direction to take. I was hoping we could take the url icon out of the ThoughtAnnotation and make it position static.

**Comment by raineorshine** [comment]
I played around and didn't find a straightforward solution. Let's hold off on additional work since this is not a high priority.

**Comment by shresthabijay** [comment]
> Making the Thought position absolute is a dramatic change. We do that in flat render but the current layout algorithm relies on the default browser layout with staticly positioned Thoughts.

I don't mean absolutely positioning thought containers. In the current implementation there are `Thought` and `ThoughtAnnotation` side by side, while only `Thought` takes the space, since `ThoughtAnnotation`  is absolutely positioned. Allowing `ThoughtAnnotation` to take space and positioning `Thought` actually solves the problem. Only problem is cursor overlay styles seems to be affected. 

I have sent a PR making the changes. We can keep it on hold, if it is not the solution we want.

**Comment by baproactive** [comment]
Hi @raineorshine 
I can't replicate this issue on the latest main branch. 

Can you check if this is still happening from your side as well?
